### ISSUE TITLE
gradle compatibility

### ISSUE THREAD

**Issue by eslamabdalgwadmohamed** [evilrat/flutter_zoom_sdk#1]
when add dependency with grade version com.android.tools.build:gradle:4.1.0 and 3.5.4 and other

**worked with version 3.4.3**

Execution failed for task ':flutter_zoom_sdk:bundleReleaseAar'.         
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :flutter_zoom_sdk project caused this error: /Users/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-0.0.2/android/libs/commonlib/commonlib.aar, /Users/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-0.0.2/android/libs/mobilertc/mobilertc.aar

**Comment by evilrat** [comment]
Change Gradle on project level build Gradle to 3.4.0 and make sure to keep minSdkVersion to 21 or +

Progruard also need to be there

-keep class  us.zoom.**{*;}
-keep class  com.zipow.**{*;}
-keep class  us.zipow.**{*;}
-keep class  org.webrtc.**{*;}
-keep class  us.google.protobuf.**{*;}
-keep class  com.google.crypto.tink.**{*;}
-keep class  androidx.security.crypto.**{*;}


buildTypes {
        release {
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }


add this on app level build Gradle

**Comment by AlexandrFarkas** [comment]
Hey, @evilrat. 
Why you cannot place this rules to the package itself?

**Comment by evilrat** [comment]
will update that in next release....thanks for sugession
