### ISSUE TITLE
Update zoom sdk , android version , ios version

### ISSUE THREAD

**Issue by hopee-tien** [evilrat/flutter_zoom_sdk#108]

**Comment by raj-wv** [comment]
i have made it my self ,share with you guys in 3 days around because there is still some issue

**Comment by tien-hopee** [comment]
@raj-wv  
we upgraded it in our fork. sdk 5.12. Nice if you do it too. thank you so much

**Comment by AthulRk** [comment]
@raj-wv We are also facing same problem. Waiting for the Solution. Thanks in advance

**Comment by johntyty912** [comment]
I am facing this issue too. Please help.

**Comment by Ahmed-3lam** [comment]
I am facing this issue too

**Comment by raj-wv** [comment]
add this in your depandency and enjoy!
![Screenshot 2022-12-16 at 11 14 14 AM](https://user-images.githubusercontent.com/96932156/208030746-019b954a-1e50-42b2-b118-f4ceaf97b28f.png)



flutter_zoom:
    git:
      url: https://github.com/raj-wv/flutter_zoom.git
      ref: zoom-sdk-5_12_plus_android_ios_new


after running pub get 
to download mobilertc.aar and commonlib.aar 
run this :- flutter pub run flutter_zoom:unzip_zoom

**Comment by AthulRk** [comment]
@raj-wv facing error 
 Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android:flexbox:2.0.1.

**Comment by hopee-tien** [comment]
issue has fix by me in my repository 
https://github.com/tienhopee/flutter_zoom_plugin_2023
