### ISSUE TITLE
What are the input string for viewOptions

### ISSUE THREAD

**Issue by faslurrajah** [evilrat/flutter_zoom_sdk#11]
I'm using Dev Channel and I want to hide meeting ID, password & invite links in the UI of Android & iOS. I tried viewOption

viewOptions = MeetingViewsOptions.NO_TEXT_PASSWORD + MeetingViewsOptions.NO_TEXT_MEETING_ID 
in the ZoomMeetingOptions. No changes found.

Any advices?

**Comment by evilrat** [comment]
when meeting starts...you can see zoom logo on top middle....which can be hidden via making viewoptions = true.....so if there is no zoom icon there is no option see meeting id and pass

**Comment by faslurrajah** [comment]
setting viewoption='true' worked.

**Comment by faslurrajah** [comment]
setting viewoption='true' is not working with iOS simulator ?

**Comment by evilrat** [comment]
> viewoption='true' is

will check ......and fix it as soon as possible
