### ISSUE TITLE
Release SDK

### ISSUE THREAD

**Issue by faslurrajah** [evilrat/flutter_zoom_sdk#12]
Which iOS zoom sdk is used by dev branch of flutter_zoom_sdk ? 

<img width="900" alt="image" src="https://user-images.githubusercontent.com/30668705/129534532-36ff30df-7fbf-4cb0-ae96-ad6f673d3992.png">

Here they mentioned two different SDK for  both emulators and real devices.  Can I release the app to App Store which this dev branch build?

**Comment by evilrat** [comment]
yes
