### ISSUE TITLE
flutter_zoom_sdk Initialize Error

### ISSUE THREAD

**Issue by Ghoral** [evilrat/flutter_zoom_sdk#14]
I/flutter (11841): Created the view //from zoom view controller
E/AndroidRuntime(11841): FATAL EXCEPTION: main
E/AndroidRuntime(11841): Process: com.example.zoom, PID: 11841
E/AndroidRuntime(11841): java.lang.ExceptionInInitializerError
E/AndroidRuntime(11841):        at com.zipow.cmmlib.AppContext.d(Unknown Source:0)
E/AndroidRuntime(11841):        at e.b.b.e0.p(Unknown Source:108)
E/AndroidRuntime(11841):        at b.a.a.e.x(Unknown Source:111)
E/AndroidRuntime(11841):        at b.a.a.e.s(Unknown Source:109)
E/AndroidRuntime(11841):        at c.a.c.a.j$a.a(Unknown Source:17)
E/AndroidRuntime(11841):        at io.flutter.embedding.engine.e.b.e(Unknown Source:57)
E/AndroidRuntime(11841):        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/AndroidRuntime(11841):        at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(11841):        at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime(11841):        at android.os.Looper.loop(Looper.java:183)
E/AndroidRuntime(11841):        at android.app.ActivityThread.main(ActivityThread.java:7664)
E/AndroidRuntime(11841):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11841):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(11841):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(11841): Caused by: java.lang.ClassNotFoundException: com.zipow.cmmlib.AppUtil
E/AndroidRuntime(11841):        at java.lang.Runtime.nativeLoad(Native Method)
E/AndroidRuntime(11841):        at java.lang.Runtime.nativeLoad(Runtime.java:1131)
E/AndroidRuntime(11841):        at java.lang.Runtime.loadLibrary0(Runtime.java:1085)
E/AndroidRuntime(11841):        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
E/AndroidRuntime(11841):        at java.lang.System.loadLibrary(System.java:1664)
E/AndroidRuntime(11841):        at com.zipow.cmmlib.AppContext.<clinit>(Unknown Source:17)
E/AndroidRuntime(11841):        ... 14 more

 minSdkVersion 21
 targetSdkVersion 30

While running in release mode I am getting this error in controller.initZoom(this.zoomOptions1
). Works perfectly in debug mode.

![code](https://user-images.githubusercontent.com/49188349/130343431-2cad969f-2d9d-467b-b36f-cb454abfa89a.png)

**Comment by evilrat** [comment]
Setup proguard rules

**Comment by Ghoral** [comment]
-keep class com.shockwave.**
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }

-keep class us.zoom.{*;}
-keep class com.zipow.{*;}
-keep class us.zipow.**{*;}
-keep class org.webrtc.{*;}
-keep class us.google.protobuf.{*;}
-keep class com.google.crypto.tink.**{*;}
-keep class androidx.security.crypto.**{*;}

This my proguard-rules.pro file.

and this is my app/build.gradle file
def keystoreProperties = new Properties()
   def keystorePropertiesFile = rootProject.file('key.properties')
   if (keystorePropertiesFile.exists()) {
       keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
   }

 buildTypes {
       release {
            minifyEnabled true
            shrinkResources true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
           signingConfig signingConfigs.release
       }

**Comment by evilrat** [comment]
Remove shrink resources and please try to run by cloning repo...and also
send flutter doctor log

**Comment by lovishhamal** [comment]
This is my flutter doctor log
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-NP)
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.59.1)
[✓] Connected device (2 available)

• No issues found!

I removed useShrink and cloned the repo also but still could not fix the issue.
I got this error while running example folder.

FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Gradle could not start your build.                                      
> Cannot create service of type TaskExecuter using method ProjectExecutionServices.createTaskExecuter() as there is a problem with parameter #17 of type ReservedFileSystemLocationRegistry.
   > Cannot create service of type ReservedFileSystemLocationRegistry using method ProjectExecutionServices.createReservedFileLocationRegistry() as there is a problem with parameter #1 of type List<ReservedFileSystemLocation>.
      > Could not create service of type ExecutionHistoryStore using ExecutionGradleServices.createExecutionHistoryStore().
         > Cannot lock execution history cache (/Users/lovishhamal/Desktop/pop/flutter_zoom_sdk/example/android/.gradle/6.5/executionHistory) as it has already been locked by this process.

**Comment by Ghoral** [comment]
This is my flutter doctor log
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-x64, locale
en-NP)
[✓] Android toolchain - develop for Android devices (Android SDK version
30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.59.1)
[✓] Connected device (2 available)

• No issues found!

I removed useShrink and cloned the repo also but still could not fix the issue.
I got this error while running example folder.

FAILURE: Build failed with an exception.

What went wrong:
Gradle could not start your build.
Cannot create service of type TaskExecuter using method ProjectExecutionServices.createTaskExecuter() as there is a problem with parameter #17 of type ReservedFileSystemLocationRegistry.
Cannot create service of type ReservedFileSystemLocationRegistry using method ProjectExecutionServices.createReservedFileLocationRegistry() as there is a problem with parameter #1 of type List.
> Could not create service of type ExecutionHistoryStore using ExecutionGradleServices.createExecutionHistoryStore().
> Cannot lock execution history cache (/Users/lovishhamal/Desktop/pop/flutter_zoom_sdk/example/android/.gradle/6.5/executionHistory) as it has already been locked by this process.

**Comment by evilrat** [comment]
Run flutter clean and remove .lock file inside .gradle folder

**Comment by Ghoral** [comment]
There are multiple errors.

1. I tried running without any changes I get this issue.
https://github.com/evilrat/flutter_zoom_sdk/issues/14#issuecomment-903535349

2. I changed gradle 6.5 to 6.7. 
The project runs successfully but while trying to join the meeting I get the first error I posted.
    
Also, there is no lock file and I tried gradlew clean and flutter clean both.

**Comment by evilrat** [comment]
Change gradle to 4.1.0 and check again

**Comment by Ghoral** [comment]
The gradle is 4.1.0.
I was talking about this one.

gradle/wrapper
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip

**Comment by Ghoral** [comment]
Are there going to be any updates on this?

I am getting this error while trying to build with proguard. Seems the issue is with proguard.

/Users/me/Desktop/untitled folder/flutter_zoom_sdk/example/android/app/proguard-rules.pro:2:24: R8: Expected char '}' at /Users/me/Desktop/untitled folder/flutter_zoom_sdk/example/android/app/proguard-rules.pro:2:24
-keep class com.zipow.{;}                                               
                       ^                                                
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:minifyReleaseWithR8'.                   
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: offset: 48, line: 2, column: 24, origin: /Users/me/Desktop/untitled folder/flutter_zoom_sdk/example/android/app/proguard-rules.pro
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org

**Comment by Ghoral** [comment]
@mauricioluz @evilrat is it still in development. I was really hoping for an update for a month, since my app heavily depends on this package.
Thank you.

**Comment by Ghoral** [comment]
@evilrat  I am closing thois issue..issue has been solved after adding android:name="io.flutter.app.FlutterApplication" to android.xml file. 

and thi proguard rule 
-keep class us.zoom.** { *; }
-keep class com.zipow.** { *; }
-keep class us.zipow.** { *; }
-keep class org.webrtc.** { *; }
-keep class us.google.protobuf.** { *; }
-keep class com.google.crypto.tink.** { *; }
-keep class androidx.security.crypto.** { *; }

Waiting for andorid v2 embedding and ios. 

P.s: Thankuyou for this package.
