### ISSUE TITLE
Android Embedding v2

### ISSUE THREAD

**Issue by f1forhelp** [evilrat/flutter_zoom_sdk#18]
The plugin `flutter_zoom_sdk` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are a plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

Please take a look at this because of this I am getting crashes on few devices.

---------Flutter Version -------
Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision 4cc385b4b8 (3 days ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0

**Comment by evilrat** [comment]
> The plugin `flutter_zoom_sdk` uses a deprecated version of the Android embedding.
> To avoid unexpected runtime failures or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
> If you are a plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
> 
> Please take a look at this because of this I am getting crashes on few devices.
> 
> ---------Flutter Version -------
> Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 4cc385b4b8 (3 days ago) • 2021-09-07 23:01:49 -0700
> Engine • revision f0826da7ef
> Tools • Dart 2.14.0

ok sure....soon will upgrade to embedding v2

**Comment by f1forhelp** [comment]
> > The plugin `flutter_zoom_sdk` uses a deprecated version of the Android embedding.
> > To avoid unexpected runtime failures or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
> > If you are a plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
> > Please take a look at this because of this I am getting crashes on few devices.
> > ---------Flutter Version -------
> > Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
> > Framework • revision 4cc385b4b8 (3 days ago) • 2021-09-07 23:01:49 -0700
> > Engine • revision f0826da7ef
> > Tools • Dart 2.14.0
> 
> ok sure....soon will upgrade to embedding v2

Tnx for replying can u please make it quick its kind of urgent

**Comment by evilrat** [comment]
> > > The plugin `flutter_zoom_sdk` uses a deprecated version of the Android embedding.
> > > To avoid unexpected runtime failures or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
> > > If you are a plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
> > > Please take a look at this because of this I am getting crashes on few devices.
> > > ---------Flutter Version -------
> > > Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
> > > Framework • revision 4cc385b4b8 (3 days ago) • 2021-09-07 23:01:49 -0700
> > > Engine • revision f0826da7ef
> > > Tools • Dart 2.14.0
> > 
> > 
> > ok sure....soon will upgrade to embedding v2
> 
> Tnx for replying can u please make it quick its kind of urgent

ok sure.....our team is working on it

**Comment by f1forhelp** [comment]
> > > > The plugin `flutter_zoom_sdk` uses a deprecated version of the Android embedding.
> > > > To avoid unexpected runtime failures or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
> > > > If you are a plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
> > > > Please take a look at this because of this I am getting crashes on few devices.
> > > > ---------Flutter Version -------
> > > > Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
> > > > Framework • revision 4cc385b4b8 (3 days ago) • 2021-09-07 23:01:49 -0700
> > > > Engine • revision f0826da7ef
> > > > Tools • Dart 2.14.0
> > > 
> > > 
> > > ok sure....soon will upgrade to embedding v2
> > 
> > 
> > Tnx for replying can u please make it quick its kind of urgent
> 
> ok sure.....our team is working on it

Hii @evilrat  is it done and live as I can't find any update and this issue is closed please let me know it's kind of urgent.

**Comment by justshreyas** [comment]
Any updates on this? @evilrat

**Comment by evilrat** [comment]
> > > > > The plugin `flutter_zoom_sdk` uses a deprecated version of the Android embedding.
> > > > > To avoid unexpected runtime failures or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
> > > > > If you are a plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
> > > > > Please take a look at this because of this I am getting crashes on few devices.
> > > > > ---------Flutter Version -------
> > > > > Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
> > > > > Framework • revision 4cc385b4b8 (3 days ago) • 2021-09-07 23:01:49 -0700
> > > > > Engine • revision f0826da7ef
> > > > > Tools • Dart 2.14.0
> > > > 
> > > > 
> > > > ok sure....soon will upgrade to embedding v2
> > > 
> > > 
> > > Tnx for replying can u please make it quick its kind of urgent
> > 
> > 
> > ok sure.....our team is working on it
> 
> Hii @evilrat is it done and live as I can't find any update and this issue is closed please let me know it's kind of urgent.

please check...it's already updated
