### ISSUE TITLE
Not able to start the meeting with available data

### ISSUE THREAD

**Issue by abhishekts** [evilrat/flutter_zoom_sdk#19]
Hi @evilrat , 

We are facing a problem in navigating to StartMeetingWidget, the meeting screen won't appear and the loader keeps loading in the screen which comes before the meeting screen. As mentioned in params we have only the below data which we currently using to start meeting from native android and there is working perfectly fine. I am not able to find any such arguments which could be passed to ZoomMeetingOptions. Below is data which we have which we are making use of to start meeting on android native app and tried using same on flutter too,

- zak
- meetingId
- meetingPassword
- zoomToken / JWT
- zoom appKey and secretKey

Kindly let us know how to proceed further with this and what all data is mandatory to be passed to launch the meeting.

**Comment by abhishekts** [comment]
@evilrat also tried with passing only user id / hostid and password..but still no luck.
logs as per below
![Screenshot from 2021-09-17 09-11-57](https://user-images.githubusercontent.com/87636024/133720725-e520dfcd-9276-4250-9c3e-4088b852b5f7.png)

**Comment by abhishekts** [comment]
@evilrat @mauricioluz any update on this ?

**Comment by abhishekts** [comment]
@evilrat @mauricioluz kindly reply as we are finding difficulty with launching meetings

**Comment by mauricioluz** [comment]
Hi @abhishekts .
You need to put ApiKey and ApiSecret in ZoomOptions and not in ZoomMeetingOptions.

Can you show how are you doing it now?

**Comment by evilrat** [comment]
i can see issue is resolved...so closing the issue...by can be reopened anytime
