### ISSUE TITLE
deprecation issue 

### ISSUE THREAD

**Issue by itsdani121** [evilrat/flutter_zoom_sdk#23]
when i run app then i show 

             The plugin `flutter_zoom_sdk` uses a deprecated version of the Android embedding. 
        To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. 
        Otherwise, consider removing it since
       a future release of Flutter will remove these deprecated APIs.
       If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: 
         https://flutter.dev/go/android-plugin-migration.

**Comment by AthulRk** [comment]
Any solution for this issue?
