### ISSUE TITLE
Getting blank screen when I  build an apk and run on real device. 

### ISSUE THREAD

**Issue by idipak** [evilrat/flutter_zoom_sdk#24]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1237], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio
[√] VS Code (version 1.59.0)
[√] Connected device (3 available)

• No issues found!

C:\Projects\fitsapp-customer-app>flutter doctor -v
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1237], locale en-US)
    • Flutter version 2.2.3 at C:\Users\PC\Documents\src\flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\PC\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\PC\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 94.0.4606.71
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 94.0.992.38

• No issues found!

**Comment by lovishhamal** [comment]
[https://github.com/evilrat/flutter_zoom_sdk/issues/28#issuecomment-987619892](url) this might help you.
Application tag change is optional

**Comment by lovishhamal** [comment]
[https://github.com/evilrat/flutter_zoom_sdk/issues/28#event-5725519485](url) check this out

**Comment by evilrat** [comment]
sign the apk and try again with new updated plugin
