### ISSUE TITLE
Deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by AthulRk** [evilrat/flutter_zoom_sdk#26]
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.

**Comment by itsdani121** [comment]
i think author leave this package for any further update.

**Comment by evilrat** [comment]
> i think author leave this package for any further update.

will release v2 embedding by 10th of December 2021

**Comment by itsdani121** [comment]
thanks a lot

**Comment by evilrat** [comment]
flutter_zoom_sdk: ^1.0.0 is released
