### ISSUE TITLE
How can i get meeting id, password and meeting url after creating the meeting, programmatically ?

### ISSUE THREAD

**Issue by Achin-verma** [evilrat/flutter_zoom_sdk#27]
Hi, I want to know that, if a host creates a meeting with his zoom login details and after creating or starting the meeting, and the host wants to invite other participants to join that meeting.   

How can the host get the meeting id, password, and meeting URL after creating the meeting, programmatically via code?

**Comment by Achin-verma** [comment]
@mauricioluz , @evilrat , pls guide me

**Comment by itsdani121** [comment]
have you found any solution i also want this method in my app

**Comment by evilrat** [comment]
> @mauricioluz , @evilrat , pls guide me

You will be abel to get meeting id and password on this upcoming realease on 10th December 2021

**Comment by Achin-verma** [comment]
@evilrat , It would be great if you can also plan the Schedule Meeting feature.

**Comment by evilrat** [comment]
> @evilrat , It would be great if you can also plan the Schedule Meeting feature. Like if the host wants to schedule the meeting, after scheduling the meeting, he will get the scheduled meeting details.

We are working on it...as it has been removed from sdk...and it needs to be implemented from zoom api
