### ISSUE TITLE
Web implementation

### ISSUE THREAD

**Issue by mauricioluz** [evilrat/flutter_zoom_sdk#3]
Are there any plans to launch for the web?

**Comment by evilrat** [comment]
By the end of this month...IOS & Web will be implemented

**Comment by mauricioluz** [comment]
Hello. News?

**Comment by evilrat** [comment]
> @evilrat  Hello. News?

Please wait....we need some time as we need to split ios Android and web.......because 100mb is acceptable on pub dev as a package

**Comment by mauricioluz** [comment]
@evilrat take a look at [this package](https://github.com/driftboat/flutter_zoom/tree/main/zoom). I think that the strategy used is good.
I'm contributor in this package, so maybe I can give some help.

**Comment by evilrat** [comment]
Sure any help is appreciated

**Comment by evilrat** [comment]
web sdk is implemented on new release flutter_zoom_sdk: ^1.0.0+4
