### ISSUE TITLE
Not starting with provided meetingId

### ISSUE THREAD

**Issue by lovishhamal** [evilrat/flutter_zoom_sdk#31]
Hello, @evilrat I have one final issue.
While starting meeting with provided meeting id  it is not taking that id rather it is starting meeting with random meeting id.

For example.
Here I have passed
 
controller
            .login(
          ZoomMeetingOptions(
            userId: isZoomLogIn['email'],
            meetingPassword: isZoomLogIn['password'],
            meetingId: widget.params['meetingId'],
            disableDialIn: "true",
            disableDrive: "true",
            disableInvite: "true",
            disableShare: "true",
            noAudio: "false",
            disableTitlebar: "false",
            viewOptions: "false",
            noDisconnectAudio: "false",
          ),
        )

It is not taking this meetingId and so others are unable to join with that meeting id.
Or am I missing something?.
Thank you.

**Comment by evilrat** [comment]
currently meeting id params are not working for start meeting........it will auto generate meeting id and pass......which currently cannot be retrieved programmatically.......which will be possible on next release by 10th December 2021

**Comment by Ghoral** [comment]
@evilrat issue still persists.

here is my code 
 zoom.startMeeting(
                          ZoomMeetingOptions(
                            userId: emailController.text,
                            userPassword: passwordController.text,
                            meetingId: classInfo.meetingId.toString(),
                            disableDialIn: "true",
                            disableDrive: "true",
                            disableInvite: "true",
                            disableShare: "true",
                            noAudio: "false",
                            disableTitlebar: "false",
                            viewOptions: "false",
                            noDisconnectAudio: "false",
                          ),
                        )
               
It still generates a random id and does not start with the provided meetingId.
It was written fixed in the latest docs..so please help me.

**Comment by lovishhamal** [comment]
resolved needed to to startwithName
