### ISSUE TITLE
Commonlib error

### ISSUE THREAD

**Issue by Ghoral** [evilrat/flutter_zoom_sdk#32]
@evilrat I am facing this issue while running the project version 0.0.8

Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find :commonlib:.
     Searched in the following locations:
       - file:/Users/user/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-0.0.8/android/libs/commonlib.aar
     Required by:
         project :app > project :flutter_zoom_sdk
   > Could not find :mobilertc:.
     Searched in the following locations:
       - file:/Users/user/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-0.0.8/android/libs/mobilertc.aar
     Required by:
         project :app > project :flutter_zoom_sdk

**Comment by Ghoral** [comment]
The issue is this after unzipping the file 

Download https://www.dropbox.com/s/i5fww50elzrphra/commonlib.aar?dl=1 to /Users/myname/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-0.0.8/android/libs/commonlib.aar
Unhandled exception:
FileSystemException: Cannot open file, path = '/Users/mynamel/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-0.0.8/android/libs/commonlib.aar' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
<asynchronous suspension>
pub finished with exit code 255

**Comment by evilrat** [comment]
> The issue is this after unzipping the file
> 
> Download https://www.dropbox.com/s/i5fww50elzrphra/commonlib.aar?dl=1 to /Users/myname/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-0.0.8/android/libs/commonlib.aar Unhandled exception: FileSystemException: Cannot open file, path = '/Users/mynamel/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-0.0.8/android/libs/commonlib.aar' (OS Error: No such file or directory, errno = 2) #0 _File.open. (dart:io/file_impl.dart:356:9) pub finished with exit code 255

go to this path

 '/Users/mynamel/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-0.0.8/android/'

and create 'libs' folder

it will work like charm


will fix this issue soon

**Comment by Ghoral** [comment]
@evilrat  download was successful,
but now I have this error 

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.exoplayer2.ui.package-info found in modules jetified-exoplayer-common-2.14.1-runtime (com.google.android.exoplayer:exoplayer-common:2.14.1) and jetified-exoplayer-ui-2.12.3-runtime (com.google.android.exoplayer:exoplayer-ui:2.12.3)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

Please tell me how to fix this.
Thannk you.

**Comment by Ghoral** [comment]
@evilrat  issue is fixed after adding 
implementation('com.google.android.exoplayer:exoplayer:2.14.1') to app/build.gradle
