### ISSUE TITLE
When I'm running this command then facing following issue:-flutter pub run flutter_zoom_sdk:unzip_zoom_sdk

### ISSUE THREAD

**Issue by chandan123-pradhan** [evilrat/flutter_zoom_sdk#35]
Download https://www.dropbox.com/s/i5fww50elzrphra/commonlib.aar?dl=1 to C:/Users/Tiwari%20computer/Downloads/flutter_zoom_sdk-master/android/libs/commonlib.aar
Unhandled exception:
FileSystemException: Cannot open file, path = 'C:/Users/Tiwari%20computer/Downloads/flutter_zoom_sdk-master/android/libs/commonlib.aar' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
<asynchronous suspension>
pub finished with exit code 255

**Comment by evilrat** [comment]
go to 'C:/Users/Tiwari%20computer/Downloads/flutter_zoom_sdk-master/android/' this directory and create libs folder and re run command
