### ISSUE TITLE
Join Meeting without checking if the host has started the meeting and claim as host

### ISSUE THREAD

**Issue by ayu8899** [evilrat/flutter_zoom_sdk#39]
I have a scheduled meet with zoom api (with waiting room true and join before host is false) and later **Join meeting** with this flutter zoom sdk. 
However it seems that it  didn't check if the waiting room is true or if the meeting is started by host.  Participant can just join the meet without these two checking.  Participant can also claim as host later on.

@evilrat can guide me? any additional setting need to be done? expect the join meet to have check if the host has started the meet and no claim as host option to be available for participant.

joinMeeting(BuildContext context) {
    Timer timer;

bool _isMeetingEnded(String status) {
      var result = false;

      if (Platform.isAndroid)
        result = status == "MEETING_STATUS_DISCONNECTING" || status == "MEETING_STATUS_FAILED";
      else
        result = status == "MEETING_STATUS_IDLE";
      return result;
    }

      ZoomOptions zoomOptions = new ZoomOptions(
        domain: "zoom.us",
        appKey: "xxx", //API KEY FROM ZOOM
        appSecret: "xxx", //API SECRET FROM ZOOM
      );
      var meetingOptions = new ZoomMeetingOptions(
          userId: 'test', //pass username for join meeting only --- Any name eg:- EVILRATT.
          meetingId: '89950099xxx', //pass meeting id for join meeting only
          meetingPassword: 'xxx', //pass meeting password for join meeting only
          disableDialIn: "true",
          disableDrive: "true",
          disableInvite: "true",
          disableShare: "true",
          disableTitlebar: "false",
          viewOptions: "false",
          noAudio: "false",
          noDisconnectAudio: "false"
      );

      var zoom = ZoomView();
      zoom.initZoom(zoomOptions).then((results) {
        if(results[0] == 0) {
          zoom.onMeetingStatus().listen((status) {
            print("[Meeting Status Stream] : " + status[0] + " - " + status[1]);
            if (_isMeetingEnded(status[0])) {
              print("[Meeting Status] :- Ended");
              timer.cancel();
            }
          });
          print("listen on event channel");
          zoom.joinMeeting(meetingOptions).then((joinMeetingResult) {
            timer = Timer.periodic(new Duration(seconds: 2), (timer) {
              zoom.meetingStatus(meetingOptions.meetingId)
                  .then((status) {
                print("[Join Meeting Status Polling] : " + status[0] + " - " + status[1]);
              });
            });
          });
        }
      }).catchError((error) {
        print("[Error Generated] : " + error);
      });
    }

**Comment by ayu8899** [comment]
@evilrat  I have tried with the old version 0.04 (when constructor onViewCreated still valid) . When Join meeting, it show waiting host to start meeting though.
With the latest version 0.08  the feature no longer wait for host to start meeting, 
when click on claim host, however,  no prompt for host key as what zoom documentation mentioned https://support.zoom.us/hc/en-us/articles/205172555-Using-your-host-key

Participant can claim as host freely

Anyone have the same issue?

**Comment by evilrat** [comment]
it is working
![WhatsApp Image 2022-01-12 at 6 35 45 PM](https://user-images.githubusercontent.com/50332657/149145962-53d1134c-102b-4ff5-a2de-756852ce0d62.jpeg)
![Screenshot 2022-01-12 at 6 37 23 PM](https://user-images.githubusercontent.com/50332657/149146017-c24d8ed0-7924-4502-8ccf-e80687582eb2.png)


Check The Screenshots

**Comment by evilrat** [comment]
follow the example code and try to recreate meeting with waiting room enabled......you are free to reopen issue if still having problem.
