### ISSUE TITLE
can we create meeting with this package

### ISSUE THREAD

**Issue by harshrs641** [evilrat/flutter_zoom_sdk#4]

**Comment by ahmedessid** [comment]
Same question.. Join meeting works very well but start meeting feature seems not working!

![image](https://user-images.githubusercontent.com/29545769/122923489-ae521900-d35c-11eb-87d9-95e436a05283.png)

**Comment by evilrat** [comment]
yes....you can start or host meeting...

https://github.com/evilrat/flutter_zoom_sdk/blob/master/example/lib/start_meeting_screen.dart

just replace these two parameter with your zoom login credentials

userId: 'username', //pass host email for zoom
meetingPassword: 'pass', //pass host password for zoom

**Comment by evilrat** [comment]
Check example app start_meeting_screen.dart and don't forget to replace
userid and meeting password paramaeter with your zoom login id and pass

**Comment by avonwagle** [comment]
How to create a meeting with specific zoom id and password? It creates a meeting with new zoom id and password

**Comment by evilrat** [comment]
> How to create a meeting with specific zoom id and password? It creates a meeting with new zoom id and password

Current not possible...as zoom provides meeting id and password itself.....you only need to lodin with your zoom credentials to start new meetings

**Comment by avonwagle** [comment]
Hello,

Can we disable screenshot and screen record option using this plugin? If
not is therw a way to implement this features

Hoping to hear from you soon

With regards
Avon

**Comment by evilrat** [comment]
Screecapture is disabled for meeting while you can use flutter_windowmanager to disable screen capture and video capture on complete app....you can do this using native code too...

**Comment by avonwagle** [comment]
I have already disabled that using native code. While using this sdk on notification, it shows zoom , how can i replace this? Also can we remove all options and provide only chat,audio,video option on meetingoption for students?

**Comment by evilrat** [comment]
Will push that update today.....removed zoom from notification & zoom icon
too from notification

**Comment by evilrat** [comment]
As you are taking of customizing toolbar...it is possible but it require
time.....will take this in consideration and try to Implemente this feature.
