### ISSUE TITLE
commonlib error

### ISSUE THREAD

**Issue by lotustha** [evilrat/flutter_zoom_sdk#40]
D:\Flutter Projects\myschoolpro>flutter pub run flutter_zoom_sdk:unzip_zoom_sdk
Download https://www.dropbox.com/s/i5fww50elzrphra/commonlib.aar?dl=1 to D:/Flutter%20Projects/myschoolpro/.dart_tool/pub/bin/flutter_zoom_sdk/unzip_zoom_sdk.dart-2.15.1.snapshot/android/libs/commonlib.aar
Unhandled exception:
FileSystemException: Cannot open file, path = 'D:/Flutter%20Projects/myschoolpro/.dart_tool/pub/bin/flutter_zoom_sdk/unzip_zoom_sdk.dart-2.15.1.snapshot/android/libs/commonlib.aar' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
<asynchronous suspension>
pub finished with exit code 255

**Comment by evilrat** [comment]
flutter sdk version?

**Comment by lotustha** [comment]
Its 2.12.0

**Comment by lotustha** [comment]
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (4 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

**Comment by evilrat** [comment]
it fixed.....check flutter_zoom_sdk: ^1.0.0
