### ISSUE TITLE
Ios build error

### ISSUE THREAD

**Issue by Ghoral** [evilrat/flutter_zoom_sdk#44]
Hello @evilrat.
While running on ios there are two issues:

On unzipping to dev and running on simulator I am getting this error:
![Screen Shot 2022-01-13 at 1 31 16 PM](https://user-images.githubusercontent.com/49188349/149288871-b33fe7d6-2da3-4afb-8a40-24af5c9f5e47.png)

On running on real device:
![Screen Shot 2022-01-13 at 1 39 54 PM](https://user-images.githubusercontent.com/49188349/149288944-b9587ea7-231d-4bf0-932d-e58a47ba7057.png)

**Comment by evilrat** [comment]
looking to reproduce the issue and will fix as soon as possible😁

**Comment by Ghoral** [comment]
Thank you..Here is the doctor report in case you need it.
Doctor sum mary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

• No issues found!

**Comment by evilrat** [comment]
Path has been release please check and verify

**Comment by Ghoral** [comment]
Sure I will do it asap.

**Comment by Ghoral** [comment]
@evilrat Ios dev(simulator) has the same issue...but working perfectly on the device.
However viewOptions: "true" is not working for ios..It is still showing the meeting information.

I will close the issue after knowing ( viewOptions: "true") is a bug or not configured correctly.. since I dont need to test on simulator.

**Comment by Ghoral** [comment]
Another issue when trying to start meeting by login user :

`  zoom.startMeetingNormal(
                          ZoomMeetingOptions(
                            userId: emailController.text,
                            userPassword: passwordController.text,
                            meetingId: classInfo.meetingId.toString(),
                            disableDialIn: "true",
                            disableDrive: "true",
                            disableInvite: "true",
                            disableShare: "true",
                            noAudio: "false",
                            disableTitlebar: "false",
                            viewOptions: "false",
                            noDisconnectAudio: "false",
                          ),
                        )`
It throws following error.
MissingPluginException(No implementation found for method startNormal on channel com.evilratt/zoom_sdk)

**Comment by evilrat** [comment]
another patch added...you need to call startMeeting as of now startMeetingNormal will not work for ios

**Comment by Ghoral** [comment]
Sure I will update it..will there be fix for view option also. That would be great as of now.

**Comment by evilrat** [comment]
yes

**Comment by Ghoral** [comment]
@evilrat meetingid is still visible..but I am closing this issue since that is not related to this thread.

**Comment by Ghoral** [comment]
@evilrat reopening the issue..I forgot to mention the issue is in joinMeeting. The meeting Id is not hidden.

**Comment by evilrat** [comment]
> Start meeting still gives this error:
> 
> MissingPluginException(No implementation found for method login on channel com.evilratt/zoom_sdk) But I can manage it for now from my side. So currently hiding meetingId is necessary for my app.

please share the solution here....

**Comment by Ghoral** [comment]
`[LayoutConstraints] Unable to simultaneously satisfy constraints.
        Probably at least one of the constraints in the following list is one you don't want. 
        Try this: 
                (1) look at each constraint and try to figure out which you don't expect; 
                (2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x282930500 'assistantHeight' TUISystemInputAssistantView:0x125f44d80.height == 45   (active)>",
    "<NSLayoutConstraint:0x2829e3610 'assistantView.bottom' TUISystemInputAssistantView:0x125f44d80.bottom == _UIKBCompatInputView:0x12729a480.top   (active)>",
    "<NSLayoutConstraint:0x2829fb1b0 'assistantView.top' V:|-(0)-[TUISystemInputAssistantView:0x125f44d80]   (active, names: '|':UIInputSetHostView:0x1394bf790 )>",
    "<NSLayoutConstraint:0x2829cfe80 'inputView.top' V:|-(0)-[_UIKBCompatInputView:0x12729a480]   (active, names: '|':UIInputSetHostView:0x1394bf790 )>"
)


Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x2829e3610 'assistantView.bottom' TUISystemInputAssistantView:0x125f44d80.bottom == _UIKBCompatInputView:0x12729a480.top   (active)>


Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[Snapshotting] Snapshotting a view (0x125f762b0, _UIReplicantView) that has not been rendered at least once requires afterScreenUpdates:YES.
flutter: e ->MissingPluginException(No implementation found for method startNormal on channel com.evilratt/zoom_sdk)`

This is complete error log

**Comment by Ghoral** [comment]
> > Start meeting still gives this error:
> > MissingPluginException(No implementation found for method login on channel com.evilratt/zoom_sdk) But I can manage it for now from my side. So currently hiding meetingId is necessary for my app.
> 
> please share the solution here....

My solution is redirecting to web for now <span>&#129315;</span>

**Comment by evilrat** [comment]
You can verify now.....everything is working as expected

**Comment by Ghoral** [comment]
Ok I will verify the changes

**Comment by evilrat** [comment]
> You can verify now.....everything is working as expected

ok and please let me know.....and also verify it it returns meeting id and password on start meeting

**Comment by Ghoral** [comment]
Ok sure...I might take some time to respond since it is already night here..but no more than 12 hours.

**Comment by evilrat** [comment]
> Ok sure...I might take some time to respond since it is already night here..but no more than 12 hours.

ok sure

**Comment by Ghoral** [comment]
@evilrat didn't want to keep work pending so I did the testing.

Works perfectly now.

Can you give me some date about when startmeetingwithNormal and meetingId hide while joining class will be released?.  So that I can do the planning.


Right now I am getting this while doing startMeetingNormal.
e ->type 'bool' is not a subtype of type 'List<dynamic>?' in type cast

Thank you.

**Comment by Ghoral** [comment]
Hello @evilrat, Seems the issue still persists in 1.0.0+5.
while startingMeetingNormal I still get the error.

`[Snapshotting] Snapshotting a view (0x13268e940, _UIReplicantView) that has not been rendered at least once requires afterScreenUpdates:YES.
[Snapshotting] Snapshotting a view (0x13268e940, _UIReplicantView) that has not been rendered at least once requires afterScreenUpdates:YES.
[LayoutConstraints] Unable to simultaneously satisfy constraints.
        Probably at least one of the constraints in the following list is one you don't want. 
        Try this: 
                (1) look at each constraint and try to figure out which you don't expect; 
                (2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x282eca7b0 'assistantHeight' TUISystemInputAssistantView:0x10d2bf2a0.height == 45   (active)>",
    "<NSLayoutConstraint:0x282e67cf0 'assistantView.bottom' TUISystemInputAssistantView:0x10d2bf2a0.bottom == _UIKBCompatInputView:0x132630530.top   (active)>",
    "<NSLayoutConstraint:0x282e67d90 'assistantView.top' V:|-(0)-[TUISystemInputAssistantView:0x10d2bf2a0]   (active, names: '|':UIInputSetHostView:0x10d0e9b90 )>",
    "<NSLayoutConstraint:0x282ecabc0 'inputView.top' V:|-(0)-[_UIKBCompatInputView:0x132630530]   (active, names: '|':UIInputSetHostView:0x10d0e9b90 )>"
)


Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x282e67cf0 'assistantView.bottom' TUISystemInputAssistantView:0x10d2bf2a0.bottom == _UIKBCompatInputView:0x132630530.top   (active)>


Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[Snapshotting] Snapshotting a view (0x13639af40, _UIReplicantView) that has not been rendered at least once requires afterScreenUpdates:YES.
Got response from start: MobileRTCMeetError
flutter: e ->type 'bool' is not a subtype of type 'List<dynamic>?' in type cast`

Did flutter clean and reinstallation of package.

Thank you.

**Comment by evilrat** [comment]
ok will fix it as soon as possible

**Comment by Ghoral** [comment]
@evilrat could also fix hide meetingId for join meeting. I would be really grateful. Since that is very important in my app.

**Comment by evilrat** [comment]
ok.....i fixed it

**Comment by Ghoral** [comment]
Thank you so much

**Comment by Ghoral** [comment]
@evilrat there seems to be some issue while building.

![Screen Shot 2022-01-14 at 4 12 00 PM](https://user-images.githubusercontent.com/49188349/149500731-3a6968d2-6f17-43de-9034-904bbd299e53.png)

**Comment by evilrat** [comment]
> @evilrat there seems to be some issue while building.
> 
> ![Screen Shot 2022-01-14 at 4 12 00 PM](https://user-images.githubusercontent.com/49188349/149500731-3a6968d2-6f17-43de-9034-904bbd299e53.png)

ok working on it to fix it

**Comment by evilrat** [comment]
> @evilrat there seems to be some issue while building.
> 
> ![Screen Shot 2022-01-14 at 4 12 00 PM](https://user-images.githubusercontent.com/49188349/149500731-3a6968d2-6f17-43de-9034-904bbd299e53.png)
> 

I am creating another branch for ios fixes....you can test that...and after successful verification can push the code to pub.dev 'ios-fixes' will be branch name

**Comment by Ghoral** [comment]
ok sure I need to clone the repo right ?

**Comment by evilrat** [comment]
> ok sure I need to clone the repo right ?

yes

**Comment by evilrat** [comment]
> ok sure I need to clone the repo right ?

check ios-fixes branch.....just add it to your package.json else everything same

**Comment by Ghoral** [comment]
@evilrat latest code has not been updated right? because the latest commit is 10 hr ago. It has the following error

![Screen Shot 2022-01-14 at 10 57 31 PM](https://user-images.githubusercontent.com/49188349/149556765-a5723c89-6510-47fe-bab4-f158aff90578.png)

**Comment by evilrat** [comment]
https://github.com/evilrat/flutter_zoom_sdk/tree/ios-fixes

**Comment by Ghoral** [comment]
@evilrat I tried this but this
![Screen Shot 2022-01-15 at 12 44 56 AM](https://user-images.githubusercontent.com/49188349/149570534-7386d769-1368-4b6d-9c18-13cb7436edb8.png)

but it me this error
![Screen Shot 2022-01-15 at 12 45 57 AM](https://user-images.githubusercontent.com/49188349/149570654-1c9cdd64-1d21-4e78-8640-ded8977a8293.png)

and I tried cloning from this -> https://github.com/evilrat/flutter_zoom_sdk/tree/ios-fixes

and this gave me this error

![Screen Shot 2022-01-15 at 12 46 59 AM](https://user-images.githubusercontent.com/49188349/149570758-775e4c26-8edd-48d4-95ce-d482c9f5ec24.png)

**Comment by evilrat** [comment]
> @evilrat I tried this but this ![Screen Shot 2022-01-15 at 12 44 56 AM](https://user-images.githubusercontent.com/49188349/149570534-7386d769-1368-4b6d-9c18-13cb7436edb8.png)
> 
> but it me this error ![Screen Shot 2022-01-15 at 12 45 57 AM](https://user-images.githubusercontent.com/49188349/149570654-1c9cdd64-1d21-4e78-8640-ded8977a8293.png)
> 
> and I tried cloning from this -> https://github.com/evilrat/flutter_zoom_sdk/tree/ios-fixes
> 
> and this gave me this error
> 
> ![Screen Shot 2022-01-15 at 12 46 59 AM](https://user-images.githubusercontent.com/49188349/149570758-775e4c26-8edd-48d4-95ce-d482c9f5ec24.png)
> 
> This also didnot work flutter_zoom_sdk: git: url: https://github.com/evilrat/flutter_zoom_sdk.git ref: ios-fixes

try to add it to your project's pubspec.yaml

flutter_zoom_sdk:
git:
url: https://github.com/evilrat/flutter_zoom_sdk.git
ref: ios-fixes

**Comment by evilrat** [comment]
> @evilrat I tried this but this ![Screen Shot 2022-01-15 at 12 44 56 AM](https://user-images.githubusercontent.com/49188349/149570534-7386d769-1368-4b6d-9c18-13cb7436edb8.png)
> 
> but it me this error ![Screen Shot 2022-01-15 at 12 45 57 AM](https://user-images.githubusercontent.com/49188349/149570654-1c9cdd64-1d21-4e78-8640-ded8977a8293.png)
> 
> and I tried cloning from this -> https://github.com/evilrat/flutter_zoom_sdk/tree/ios-fixes
> 
> and this gave me this error
> 
> ![Screen Shot 2022-01-15 at 12 46 59 AM](https://user-images.githubusercontent.com/49188349/149570758-775e4c26-8edd-48d4-95ce-d482c9f5ec24.png)
> 
> This also didnot work flutter_zoom_sdk: git: url: https://github.com/evilrat/flutter_zoom_sdk.git ref: ios-fixes

flutter_zoom_sdk: ^1.0.0+7 

Please try this

**Comment by Ghoral** [comment]
Hello @evilrat,
Everything works well with the build. Archived is also successfully build. I am closing this issue. However there is login issue in startMeetingNormal which will be posted on another thread.

Thank you.

**Comment by WaqasAli-Dev** [comment]
Anyone facing Pods issue after adding "flutter_zoom_sdk" dependencies ?
