### ISSUE TITLE
Ios implementation

### ISSUE THREAD

**Issue by Sreeharikr** [evilrat/flutter_zoom_sdk#5]

**Comment by evilrat** [comment]
Working on it...soon it will be implemented

**Comment by Sreeharikr** [comment]
> Working on it...soon it will be implemented

**Comment by devianl2** [comment]
Hopefully the new patch by today or tomorrow.

**Comment by evilrat** [comment]
got few bugs...soon pushing the update....working on customise notification & Customise UI

**Comment by devianl2** [comment]
> got few bugs...soon pushing the update....working on customise notification & Customise UI

Thanks for the effort. Do you have any targeted date to release the update?

**Comment by evilrat** [comment]
by 15th of July

**Comment by AbdouEsi** [comment]
> by 15th of July

A lot is waiting for you.. Thank you very much

**Comment by evilrat** [comment]
I see....our team is working on it....we have much more projects to do....you can expect by end of july for sure.

**Comment by F-BONAPARTA** [comment]
i hope you almost finished

**Comment by agrmay100** [comment]
@evilrat , not able to implement on ios, after installing the plugin, do i need to copy all the files in ios folder of this plugin(ios sdk is also there) to my project ios directory??

**Comment by agrmay100** [comment]
Hey, can u confirm plz if its working on ios..?
If yes, it would be great if I can get the steps to run it successfully.

**Comment by abhishekts** [comment]
@evilrat Kindly confirm when will the SDK start supporting on IOS platform as it was mentioned in the first week of August

**Comment by evilrat** [comment]
> Hey, can u confirm plz if its working on ios..?
> If yes, it would be great if I can get the steps to run it successfully.
> 
> https://github.com/evilrat/flutter_zoom_sdk/issues/6#issuecomment-884679223
> 
> getting the same error while adding the http github link with ref dev.(above link)
> 
>     ld: '/Users/mayankagrawal/Desktop/dev/flutter/.pub-cache/git/flutter_zoom_sdk-d2c789d2205f9d099fc083aa7579911612521e29/ios/MobileRTC.framework/MobileRTC' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode
>     setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file
>     '/Users/mayankagrawal/Desktop/dev/flutter/.pub-cache/git/flutter_zoom_sdk-d2c789d2205f9d099fc083aa7579911612521e29/ios/MobileRTC.framework/MobileRTC' for architecture arm64
>     clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> 
> 
Add two rows to the ios/Runner/Info.plist:

one with the key Privacy - Camera Usage Description and a usage description.

one with the key Privacy - Microphone Usage Description and a usage description.

<key>NSCameraUsageDescription</key>
<string>Need to use the camera for call</string>
<key>NSMicrophoneUsageDescription</key>
<string>Need to use the microphone for call</string>


Disable Bitcode in ios/Podfile:

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

NOTE for testing on the iOS simulator

flutter pub run flutter_zoom_sdk:unzip_zoom_sdk dev

Run this command after testing:
flutter pub run flutter_zoom_sdk:unzip_zoom_sdk

**Comment by evilrat** [comment]
> @evilrat Kindly confirm when will the SDK start supporting on IOS platform as it was mentioned in the first week of August

You can run it using dev branch ......

**Comment by evilrat** [comment]
> @evilrat Kindly confirm when will the SDK start supporting on IOS platform as it was mentioned in the first week of August

Sorry for the delay....as we cannot push package above 100mb we no need to split sdk....we need some time......as we are working on ther other projects
