### ISSUE TITLE
Hide MeetingId

### ISSUE THREAD

**Issue by Ghoral** [evilrat/flutter_zoom_sdk#51]
Hello @evilrat,
While joining the meeting the meetingId is still visible. This seems to be the last and important enhancement for ios.

![IMG-4256](https://user-images.githubusercontent.com/49188349/149613184-05757bb0-efb1-4685-8e2d-cee87b348167.png)

**Comment by evilrat** [comment]
> Hello @evilrat, While joining the meeting the meetingId is still visible. This seems to be the last and important enhancement for ios.
> 
> ![IMG-4256](https://user-images.githubusercontent.com/49188349/149613184-05757bb0-efb1-4685-8e2d-cee87b348167.png)

looking into it

**Comment by Achin-verma** [comment]
Hi, @evilrat, i also want to hide these meeting details for the ios, any update on this, how can I hide it?

**Comment by evilrat** [comment]
> Hi, @evilrat, i also want to hide these meeting details for the ios, any update on this, how can I hide it?

can you check it it is working or not
