### ISSUE TITLE
ios build error : Adjacent operators are in non-associative precedence group 'ComparisonPrecedence'

### ISSUE THREAD

**Issue by Iam-that-Chic** [evilrat/flutter_zoom_sdk#52]
![image](https://user-images.githubusercontent.com/58329717/149652023-7e47a2a2-73bf-4052-a6fa-7b16df36f02f.png)

**Comment by evilrat** [comment]
> ![image](https://user-images.githubusercontent.com/58329717/149652023-7e47a2a2-73bf-4052-a6fa-7b16df36f02f.png)

which version you are using.......please use latest version flutter_zoom_sdk: ^1.0.0+7
