### ISSUE TITLE
flutter_zoom_web.dart:3:8: Error: Not found: 'dart:js' import 'dart:js';

### ISSUE THREAD

**Issue by dromedian** [evilrat/flutter_zoom_sdk#53]
I followed the instructions to add the module to ios, but when I compile it I get this error.
I'm not compiling for web, but straight on a device.

what am I doing wrong??

Xcode 13 - iOS 14

**Comment by evilrat** [comment]
please send complete error log

**Comment by FaizanFarooq12** [comment]
Hi. Same issue occurred when building for android. Copied your example code to test and got these errors when building app for android emulator.
<img width="1440" alt="Screenshot 2022-01-18 at 5 46 07 PM" src="https://user-images.githubusercontent.com/93262470/149940822-e493ae21-e694-4f8b-9a25-1ca6b506fe43.png">
<img width="1440" alt="Screenshot 2022-01-18 at 5 46 11 PM" src="https://user-images.githubusercontent.com/93262470/149940840-cab2867b-5622-425b-9dad-b68f255a2cca.png">
<img width="1440" alt="Screenshot 2022-01-18 at 5 46 15 PM" src="https://user-images.githubusercontent.com/93262470/149940846-4eb7fd1e-b67e-4bf5-bcc9-2c538c22342a.png">
<img width="1440" alt="Screenshot 2022-01-18 at 5 46 18 PM" src="https://user-images.githubusercontent.com/93262470/149940852-e65f7ea4-aeb6-428c-8da3-71aa92d27374.png">
<img width="1440" alt="Screenshot 2022-01-18 at 5 46 21 PM" src="https://user-images.githubusercontent.com/93262470/149940857-ddc968b7-98f9-4410-83c8-0eecc290edc7.png">
<img width="1440" alt="Screenshot 2022-01-18 at 5 46 25 PM" src="https://user-images.githubusercontent.com/93262470/149940861-c3c96f33-d318-4e93-be68-44135e0b7fcf.png">
<img width="1440" alt="Screenshot 2022-01-18 at 5 46 31 PM" src="https://user-images.githubusercontent.com/93262470/149940867-b11a15aa-7466-450d-aae1-903aefcafac8.png">
<img width="1440" alt="Screenshot 2022-01-18 at 5 46 36 PM" src="https://user-images.githubusercontent.com/93262470/149940870-84278f4f-8926-435f-97e7-6272deedcc5d.png">
<img width="1440" alt="Screenshot 2022-01-18 at 5 46 38 PM" src="https://user-images.githubusercontent.com/93262470/149940873-b3db9515-d0ba-4d9d-b276-23e39eb4339d.png">
<img width="1440" alt="Screenshot 2022-01-18 at 5 46 41 PM" src="https://user-images.githubusercontent.com/93262470/149940878-2cf0eec1-a12b-45ca-8c78-318544216899.png">
<img width="1440" alt="Screenshot 2022-01-18 at 5 46 52 PM" src="https://user-images.githubusercontent.com/93262470/149940881-26835f2e-8da0-46c0-b57c-5af9cfc41846.png">
<img width="1440" alt="Screenshot 2022-01-18 at 5 46 58 PM" src="https://user-images.githubusercontent.com/93262470/149940883-27a6332c-0ca5-4499-9455-6f981d5e6fc6.png">
<img width="1440" alt="Screenshot 2022-01-18 at 5 47 00 PM" src="https://user-images.githubusercontent.com/93262470/149940887-4e2ed303-0364-4d0c-9c6f-91f045901da3.png">

**Comment by albert0m** [comment]
yes, this is the same stack trace I get!

**Comment by Fanatic6** [comment]
is anyone able to solve this?

**Comment by tobi-ayeni** [comment]
it is the websdk that is throwing that error. If you are not building for web, you can remove that line of code

**Comment by Fanatic6** [comment]
these are a lot of lines of code in multiple scripts that are read only and are part of the package. how to delete those as deleting those will make all the package scripts full of errors.

**Comment by Fanatic6** [comment]
Tank you tobi-ayeni for the response.
So what i did is i commented the flutter_zoom_web.dart file. Commenting it would give some errors in your script where zoomOptions and zoomMeetingOptions objects are being used as they were being imported from flutter_zoom_web.dart file. But they are also written in zoom_options.dart file. so just import that in your script where you are using these objects and the errors would go away. I have tested it and i can join as well as start meetings from my application.

**Comment by albert0m** [comment]
yeah beside the workaround of commenting stuff, this is not working out of the box. I downloaded and ran the example but I get the error.

**Comment by Fanatic6** [comment]
Yes to make the example work on mobile platform you have to coment/delete the web file

**Comment by evilrat** [comment]
> Yes to make the example work on mobile platform you have to comment/delete the web file

working on it to fix the issue....will release the patch soon

**Comment by Fanatic6** [comment]
> working on it to fix the issue....will release the patch soon

Great! Thank You!

**Comment by evilrat** [comment]
> > working on it to fix the issue....will release the patch soon
> 
> Great! Thank You!

currrently you can import

import 'package:flutter_zoom_sdk/zoom_options.dart'

in place of 

import 'package:flutter_zoom_sdk/flutter_zoom_web.dart';

**Comment by Fanatic6** [comment]
> > > working on it to fix the issue....will release the patch soon
> > 
> > 
> > Great! Thank You!
> 
> currrently you can import
> 
> import 'package:flutter_zoom_sdk/zoom_options.dart'
> 
> in place of
> 
> import 'package:flutter_zoom_sdk/flutter_zoom_web.dart';

Yes that is how i am using it currently
