### ISSUE TITLE
How can we get meeting id of a newly  created meeting

### ISSUE THREAD

**Issue by itsAyyazdev** [evilrat/flutter_zoom_sdk#57]
"NOT ISSUE": As we create a new meeting it redirects us to the zoom UI, Is there any way we could still get a meeting id or create an invitation link before proceeding to zoom UI :(

**Comment by evilrat** [comment]
> "NOT ISSUE": As we create a new meeting it redirects us to the zoom UI, Is there any way we could still get a meeting id or create an invitation link before proceeding to zoom UI :(

you get meeting id and pass...programmatically check example and readme

**Comment by itsAyyazdev** [comment]
> > "NOT ISSUE": As we create a new meeting it redirects us to the zoom UI, Is there any way we could still get a meeting id or create an invitation link before proceeding to zoom UI :(
> 
> you get meeting id and pass...programmatically check example and readme

Yeah Found it in meeting details listener, but  can we somehow get the same id and password as we get on clicking on invite in the zoom UI?

**Comment by evilrat** [comment]
> > > "NOT ISSUE": As we create a new meeting it redirects us to the zoom UI, Is there any way we could still get a meeting id or create an invitation link before proceeding to zoom UI :(
> > 
> > 
> > you get meeting id and pass...programmatically check example and readme
> 
> Yeah Found it in meeting details listener, but can we somehow get the same id and password as we get on clicking on invite in the zoom UI?

meeting id and pass are same........as shown in zoom ui......as both are generated on zoom sdk
