### ISSUE TITLE
App size is increased after adding zoom plugin

### ISSUE THREAD

**Issue by itsAyyazdev** [evilrat/flutter_zoom_sdk#58]
Application size is exponentially increased after adding this plugin, is there anything wrong with the integration or I'm missing something?

before:
android: 37mb
ios: 66 MB

After:
android: 361mb
iOS: 178mb

**Comment by evilrat** [comment]
> Application size is exponentially increased after adding this plugin, is there anything wrong with the integration or I'm missing something?
> 
> before: android: 37mb ios: 66 MB
> 
> After: android: 361mb iOS: 178mb

https://devsupport.zoom.us/hc/en-us/articles/360059893532-How-to-reduce-APK-size-after-adding-the-Meeting-SDK-to-your-project
