### ISSUE TITLE
Issue while building/Running IOS App

### ISSUE THREAD

**Issue by abhishekts** [evilrat/flutter_zoom_sdk#6]
Hi @evilrat ,
We are not able to run or build the IOS app using the plugin. We get below attached error if we try to run. Can you check this.
![WhatsApp Image 2021-07-16 at 2 14 46 PM](https://user-images.githubusercontent.com/87636024/126114868-d30fac78-bb17-4f07-9f1a-9565179114af.jpeg)

**Comment by evilrat** [comment]
No implementation for ios...work is complete but package side crosses 100mb so unable to upload it for now...will do it by first week on aug

**Comment by evilrat** [comment]
> Hi @evilrat ,
> We are not able to run or build the IOS app using the plugin. We get below attached error if we try to run. Can you check this.
> ![WhatsApp Image 2021-07-16 at 2 14 46 PM](https://user-images.githubusercontent.com/87636024/126114868-d30fac78-bb17-4f07-9f1a-9565179114af.jpeg)
> 

If you want it anyway i can put it on github...directly as a dev branch...you can use it for now

**Comment by abhishekts** [comment]
> > Hi @evilrat ,
> > We are not able to run or build the IOS app using the plugin. We get below attached error if we try to run. Can you check this.
> > ![WhatsApp Image 2021-07-16 at 2 14 46 PM](https://user-images.githubusercontent.com/87636024/126114868-d30fac78-bb17-4f07-9f1a-9565179114af.jpeg)
> 
> If you want it anyway i can put it on github...directly as a dev branch...you can use it for now

@evilrat yes , kindly put it on github for now , we shall use it until you provide the stable release on August as you have mentioned.

**Comment by evilrat** [comment]
> > > Hi @evilrat ,
> > > We are not able to run or build the IOS app using the plugin. We get below attached error if we try to run. Can you check this.
> > > ![WhatsApp Image 2021-07-16 at 2 14 46 PM](https://user-images.githubusercontent.com/87636024/126114868-d30fac78-bb17-4f07-9f1a-9565179114af.jpeg)
> > 
> > 
> > If you want it anyway i can put it on github...directly as a dev branch...you can use it for now
> 
> @evilrat Thanks for the response. Yes , kindly put it on github for now , we shall use it until you provide the stable release on August as you have mentioned. Can you also let me when can you put the dev branch on github so that we can make internal arrangements for the release

 flutter_zoom_sdk:
    git:
      url: git@github.com:evilrat/flutter_zoom_sdk.git
      ref: dev

**Comment by abhishekts** [comment]
@evilrat Thanks for sharing , as per the above dependency I tried running pub get but it is still loading even after 30mins of time. Is this the proper way mention the implementation on yaml file
![image](https://user-images.githubusercontent.com/87636024/126214764-7ba83310-d266-4389-85d8-5310f969c584.png)

**Comment by evilrat** [comment]
> @evilrat Thanks for sharing , as per the above dependency I tried running pub get but it is still loading even after 40mins of time. Is this the proper way to mention the implementation on yaml file
> ![image](https://user-images.githubusercontent.com/87636024/126214764-7ba83310-d266-4389-85d8-5310f969c584.png)

add http link in place of ssh....and try
