### ISSUE TITLE
 lib/meeting_screen.dart:2:8: Error: Not found: 'dart:html'     import 'dart:html' hide Platform;

### ISSUE THREAD

**Issue by sugatmankar** [evilrat/flutter_zoom_sdk#60]
While Building Example app for iOS getting below error
` lib/meeting_screen.dart:2:8: Error: Not found: 'dart:html'
    import 'dart:html' hide Platform;
           ^
    ../../DevSetup/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-1.0.0+7/lib/flutter_zoom_web.dart:3:8: Error: Not found: 'dart:js'
    import 'dart:js';
           ^
    ../../DevSetup/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:13:8: Error: Not found: 'dart:html'
    import 'dart:html' as html;
           ^
    ../../DevSetup/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:6:8: Error: Not found: 'dart:html'
    import 'dart:html' as html;`

**Comment by evilrat** [comment]
> While Building Example app for iOS getting below error
> ` lib/meeting_screen.dart:2:8: Error: Not found: 'dart:html'
>     import 'dart:html' hide Platform;
>            ^
>     ../../DevSetup/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-1.0.0+7/lib/flutter_zoom_web.dart:3:8: Error: Not found: 'dart:js'
>     import 'dart:js';
>            ^
>     ../../DevSetup/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:13:8: Error: Not found: 'dart:html'
>     import 'dart:html' as html;
>            ^
>     ../../DevSetup/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:6:8: Error: Not found: 'dart:html'
>     import 'dart:html' as html;`

Please refer to issue #53
