### ISSUE TITLE
Failed to initialize zoom sdk

### ISSUE THREAD

**Issue by tffajari** [evilrat/flutter_zoom_sdk#61]
Hello, I found error

Failed to initialize Zoom SDK

and after I initialize zoom, I try to print and i get a result just like picture below

![image](https://user-images.githubusercontent.com/86940078/153126819-913edb94-001d-4957-ba7e-235d64c47e47.png)

**Comment by cool0305** [comment]
same error I got when I passed my own secret access key and api key..

**Comment by evilrat** [comment]
> same error I got when I passed my own secret access key and api key..
> 
> 

Let me check if i can reproduce the same issue

**Comment by iamgouravturka** [comment]
@tffajari @cool0305 Which api key and secret key you are using JWT or SDK
<img width="353" alt="Screenshot 2022-02-10 at 2 16 47 PM" src="https://user-images.githubusercontent.com/52244637/153370597-ae1637bb-fb0c-4871-b17f-f6333dafdeff.png">

**Comment by cool0305** [comment]
Sorry my bad, I was using the JWT app key which is not recommended....thanks for the solution @iamgouravturka

**Comment by iamgouravturka** [comment]
@evilrat we should think about it Because I also face this issue we need to change the text API Key and Secret to SDK Key and Secret.

**Comment by iamgouravturka** [comment]
@evilrat I created a PR regarding this please have a look.

**Comment by evilrat** [comment]
Already merged

**Comment by YoussefAbdelmonem** [comment]
@tffajari how did you solve this error As i got the same error 
**Failed to initialize Zoom SDK******
