### ISSUE TITLE
error: no such module 'MobileRTC' , Issue only for the IOS build

### ISSUE THREAD

**Issue by cool0305** [evilrat/flutter_zoom_sdk#64]

**Comment by cool0305** [comment]
I am facing this issue with both real devices as well as emulators while creating build.
<img width="1440" alt="Screenshot 2022-02-15 at 9 05 33 AM" src="https://user-images.githubusercontent.com/99380880/153987908-5e4bbfd6-e449-40e3-b2c5-d5264c8539af.png">

**Comment by evilrat** [comment]
> I am facing this issue with both real devices as well as emulators while creating build.
> <img width="1440" alt="Screenshot 2022-02-15 at 9 05 33 AM" src="https://user-images.githubusercontent.com/99380880/153987908-5e4bbfd6-e449-40e3-b2c5-d5264c8539af.png">
> 
> 

Did you run
flutter pub run flutter_zoom_sdk:unzip_zoom_sdk

**Comment by cool0305** [comment]
Yes I run that command as well

**Comment by evilrat** [comment]
> Yes I run that command as well

can u send the output for flutter pub run flutter_zoom_sdk:unzip_zoom_sdk and also check if file exist in that location

**Comment by SrilalS** [comment]
I'm having the same issue, but I can achieve the project. yet can't run it on IOS Simulator.

**Comment by kaushikchandru** [comment]
Any update on this please? I get the same error.

**Comment by evilrat** [comment]
> Any update on this please? I get the same error.

there might be some package causing the issue.......and try to run on real device

**Comment by rashidgondal** [comment]
Any update on this please?

**Comment by moradoronline** [comment]
I have made a "flutter clean" and it solved. Of course, do not forget to repeat the procedure to import the sdk accordingly.  Didn't test with simulator, however the iOS device worked fine after the "flutter clean"

**Comment by iamsandeepsk** [comment]
Any Solution ?

**Comment by imasif** [comment]
> > Any Solution ?
> 
> Did you tried to use "flutter clean" followed by "flutter pub get" and "flutter pub run flutter_zoom_sdk:unzip_zoom_sdk"?

Did everything, not working for Emulator.

**Comment by iamsandeepsk** [comment]
> > Any Solution ?
> 
> Did you tried to use "flutter clean" followed by "flutter pub get" and "flutter pub run flutter_zoom_sdk:unzip_zoom_sdk"?

Yes did multiple times.

**Comment by evilrat** [comment]
currently not working on iOS Emulators...............You can use real device

**Comment by tinyCoder32** [comment]
Same issue here tool, tried all the possible suggested solutions

**Comment by ark-brighthustle** [comment]
> Same issue here tool, tried all the possible suggested solutions

Please provide detail

dart version
flutter version
os
os version
Note :- will not work on mac m1 chip

**Comment by tinyCoder32** [comment]
> > Same issue here tool, tried all the possible suggested solutions
> 
> Please provide detail
> 
> dart version flutter version os os version Note :- will not work on mac m1 chip

I'm on M1, for how long is this expected to be fixed for M1 users?

**Comment by ark-brighthustle** [comment]
> > > Same issue here tool, tried all the possible suggested solutions
> > 
> > 
> > Please provide detail
> > dart version flutter version os os version Note :- will not work on mac m1 chip
> 
> I'm on M1, for how long is this expected to be fixed for M1 users?

it completely depends on zoom sdk release

**Comment by waqas-alii** [comment]
Currently flutter_zoom_sdk not worked on simulator but it works on emulator and physical devices (Android and iOS)

**Comment by moazelsawaf** [comment]
@evilrat 
If it doesn't work on simulator then why we have the following section in the documentation of the package?

**NOTE for testing on the iOS simulator**

**Comment by moazelsawaf** [comment]
I am still facing the same problem at version ^1.1.0+4, any solution to run on Simulator?

**Comment by moazelsawaf** [comment]
@evilrat 
Can you please reopen this issue?
