### ISSUE TITLE
Can't run on android sdk v-32, Targeting S+ (version 31 and above) requires that an explicit value for android:exported

### ISSUE THREAD

**Issue by Ajay9o9** [evilrat/flutter_zoom_sdk#66]
# `Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl852508837.tmp/base.apk (at Binary XML file line #148): com.evilratt.flutter_zoom_sdk.CustomWaitActivity: 

## `**Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]**
Error launching application on sdk gphone64 x86 64.

![Screenshot 2022-03-16 122046](https://user-images.githubusercontent.com/31621065/158532978-99eeaa3e-e2d2-4727-8fdc-c43ab1d2a5d4.png)

**Comment by evilrat** [comment]
Will be fixed today itself

**Comment by Ajay9o9** [comment]
@evilrat ok, you can close this after its fixed.
