### ISSUE TITLE
flutter pub run flutter_zoom_sdk:unzip_zoom_sdk not working with 1.0.0+9 version

### ISSUE THREAD

**Issue by Fanatic6** [evilrat/flutter_zoom_sdk#67]
when i run the command flutter pub run flutter_zoom_sdk:unzip_zoom_sdk with the 1.0.0+9 version it gives following errors

support@supports-MacBook-Pro edforce % flutter pub run flutter_zoom_sdk:unzip_zoom_sdk
Failed to build flutter_zoom_sdk:unzip_zoom_sdk:
../../../../flutter/packages/flutter/lib/src/foundation/basic_types.dart:9:1: Error: Not found: 'dart:ui'
export 'dart:ui' show VoidCallback;
^
../../../../flutter/packages/flutter/lib/src/foundation/binding.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show SingletonFlutterWindow, Brightness, PlatformDispatcher, window;
       ^
../../../../flutter/packages/flutter/lib/src/foundation/debug.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show Brightness;
       ^
../../../../flutter/packages/flutter/lib/src/foundation/key.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show hashValues;
       ^
../../../../flutter/packages/flutter/lib/src/foundation/stack_frame.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show hashValues;
       ^
../../../../flutter/packages/flutter/lib/src/foundation/binding.dart:107:3: Error: Type 'ui.SingletonFlutterWindow' not found.
  ui.SingletonFlutterWindow get window => ui.window;
  ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/binding.dart:128:3: Error: Type 'ui.PlatformDispatcher' not found.
  ui.PlatformDispatcher get platformDispatcher => ui.PlatformDispatcher.instance;
  ^^^^^^^^^^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:68:20: Error: Type 'VoidCallback' not found.
  void addListener(VoidCallback listener);
                   ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:72:23: Error: Type 'VoidCallback' not found.
  void removeListener(VoidCallback listener);
                      ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:106:8: Error: Type 'VoidCallback' not found.
  List<VoidCallback?> _listeners = List<VoidCallback?>.filled(0, null);
       ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:172:20: Error: Type 'VoidCallback' not found.
  void addListener(VoidCallback listener) {
                   ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:232:23: Error: Type 'VoidCallback' not found.
  void removeListener(VoidCallback listener) {
                      ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:372:20: Error: Type 'VoidCallback' not found.
  void addListener(VoidCallback listener) {
                   ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:379:23: Error: Type 'VoidCallback' not found.
  void removeListener(VoidCallback listener) {
                      ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/debug.dart:112:1: Error: Type 'ui.Brightness' not found.
ui.Brightness? debugBrightnessOverride;
^^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/binding.dart:107:46: Error: Undefined name 'window'.
  ui.SingletonFlutterWindow get window => ui.window;
                                             ^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/binding.dart:128:54: Error: Undefined name 'PlatformDispatcher'.
  ui.PlatformDispatcher get platformDispatcher => ui.PlatformDispatcher.instance;
                                                     ^^^^^^^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/binding.dart:253:46: Error: Undefined name 'Brightness'.
                debugBrightnessOverride = ui.Brightness.light;
                                             ^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/binding.dart:256:46: Error: Undefined name 'Brightness'.
                debugBrightnessOverride = ui.Brightness.dark;
                                             ^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:68:20: Error: 'VoidCallback' isn't a type.
  void addListener(VoidCallback listener);
                   ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:72:23: Error: 'VoidCallback' isn't a type.
  void removeListener(VoidCallback listener);
                      ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:106:8: Error: 'VoidCallback' isn't a type.
  List<VoidCallback?> _listeners = List<VoidCallback?>.filled(0, null);
       ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:106:41: Error: 'VoidCallback' isn't a type.
  List<VoidCallback?> _listeners = List<VoidCallback?>.filled(0, null);
                                        ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:172:20: Error: 'VoidCallback' isn't a type.
  void addListener(VoidCallback listener) {
                   ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:176:27: Error: 'VoidCallback' isn't a type.
        _listeners = List<VoidCallback?>.filled(1, null);
                          ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:178:20: Error: 'VoidCallback' isn't a type.
        final List<VoidCallback?> newListeners =
                   ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:179:18: Error: 'VoidCallback' isn't a type.
            List<VoidCallback?>.filled(_listeners.length * 2, null);
                 ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:197:18: Error: 'VoidCallback' isn't a type.
      final List<VoidCallback?> newListeners = List<VoidCallback?>.filled(_count, null);
                 ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:197:53: Error: 'VoidCallback' isn't a type.
      final List<VoidCallback?> newListeners = List<VoidCallback?>.filled(_count, null);
                                                    ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:232:23: Error: 'VoidCallback' isn't a type.
  void removeListener(VoidCallback listener) {
                      ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:235:13: Error: 'VoidCallback' isn't a type.
      final VoidCallback? _listener = _listeners[i];
            ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:334:20: Error: 'VoidCallback' isn't a type.
        final List<VoidCallback?> newListeners = List<VoidCallback?>.filled(newLength, null);
                   ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:334:55: Error: 'VoidCallback' isn't a type.
        final List<VoidCallback?> newListeners = List<VoidCallback?>.filled(newLength, null);
                                                      ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:338:17: Error: 'VoidCallback' isn't a type.
          final VoidCallback? listener = _listeners[i];
                ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:372:20: Error: 'VoidCallback' isn't a type.
  void addListener(VoidCallback listener) {
                   ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:379:23: Error: 'VoidCallback' isn't a type.
  void removeListener(VoidCallback listener) {
                      ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/debug.dart:112:4: Error: 'Brightness' isn't a type.
ui.Brightness? debugBrightnessOverride;
   ^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/key.dart:82:23: Error: The method 'hashValues' isn't defined for the class 'ValueKey<T>'.
 - 'ValueKey' is from 'package:flutter/src/foundation/key.dart' ('../../../../flutter/packages/flutter/lib/src/foundation/key.dart').
Try correcting the name to the name of an existing method, or defining a method named 'hashValues'.
  int get hashCode => hashValues(runtimeType, value);
                      ^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/foundation/stack_frame.dart:299:23: Error: The method 'hashValues' isn't defined for the class 'StackFrame'.
 - 'StackFrame' is from 'package:flutter/src/foundation/stack_frame.dart' ('../../../../flutter/packages/flutter/lib/src/foundation/stack_frame.dart').
Try correcting the name to the name of an existing method, or defining a method named 'hashValues'.
  int get hashCode => hashValues(number, package, line, column, className, method, source);
                      ^^^^^^^^^^
pub finished with exit code 1

I tried this with a new flutter project as well but still got the same error. Works fine on 1.0.0+7 version

**Comment by Ajay9o9** [comment]
Im also getting same error @evilrat

**Comment by evilrat** [comment]
> Im also getting same error @evilrat

working on it

**Comment by evilrat** [comment]
> when i run the command flutter pub run flutter_zoom_sdk:unzip_zoom_sdk with the 1.0.0+9 version it gives following errors
> 
> support@supports-MacBook-Pro edforce % flutter pub run flutter_zoom_sdk:unzip_zoom_sdk Failed to build flutter_zoom_sdk:unzip_zoom_sdk: ../../../../flutter/packages/flutter/lib/src/foundation/basic_types.dart:9:1: Error: Not found: 'dart:ui' export 'dart:ui' show VoidCallback; ^ ../../../../flutter/packages/flutter/lib/src/foundation/binding.dart:8:8: Error: Not found: 'dart:ui' import 'dart:ui' as ui show SingletonFlutterWindow, Brightness, PlatformDispatcher, window; ^ ../../../../flutter/packages/flutter/lib/src/foundation/debug.dart:5:8: Error: Not found: 'dart:ui' import 'dart:ui' as ui show Brightness; ^ ../../../../flutter/packages/flutter/lib/src/foundation/key.dart:5:8: Error: Not found: 'dart:ui' import 'dart:ui' show hashValues; ^ ../../../../flutter/packages/flutter/lib/src/foundation/stack_frame.dart:5:8: Error: Not found: 'dart:ui' import 'dart:ui' show hashValues; ^ ../../../../flutter/packages/flutter/lib/src/foundation/binding.dart:107:3: Error: Type 'ui.SingletonFlutterWindow' not found. ui.SingletonFlutterWindow get window => ui.window; ^^^^^^^^^^^^^^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/binding.dart:128:3: Error: Type 'ui.PlatformDispatcher' not found. ui.PlatformDispatcher get platformDispatcher => ui.PlatformDispatcher.instance; ^^^^^^^^^^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:68:20: Error: Type 'VoidCallback' not found. void addListener(VoidCallback listener); ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:72:23: Error: Type 'VoidCallback' not found. void removeListener(VoidCallback listener); ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:106:8: Error: Type 'VoidCallback' not found. List<VoidCallback?> _listeners = List<VoidCallback?>.filled(0, null); ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:172:20: Error: Type 'VoidCallback' not found. void addListener(VoidCallback listener) { ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:232:23: Error: Type 'VoidCallback' not found. void removeListener(VoidCallback listener) { ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:372:20: Error: Type 'VoidCallback' not found. void addListener(VoidCallback listener) { ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:379:23: Error: Type 'VoidCallback' not found. void removeListener(VoidCallback listener) { ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/debug.dart:112:1: Error: Type 'ui.Brightness' not found. ui.Brightness? debugBrightnessOverride; ^^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/binding.dart:107:46: Error: Undefined name 'window'. ui.SingletonFlutterWindow get window => ui.window; ^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/binding.dart:128:54: Error: Undefined name 'PlatformDispatcher'. ui.PlatformDispatcher get platformDispatcher => ui.PlatformDispatcher.instance; ^^^^^^^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/binding.dart:253:46: Error: Undefined name 'Brightness'. debugBrightnessOverride = ui.Brightness.light; ^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/binding.dart:256:46: Error: Undefined name 'Brightness'. debugBrightnessOverride = ui.Brightness.dark; ^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:68:20: Error: 'VoidCallback' isn't a type. void addListener(VoidCallback listener); ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:72:23: Error: 'VoidCallback' isn't a type. void removeListener(VoidCallback listener); ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:106:8: Error: 'VoidCallback' isn't a type. List<VoidCallback?> _listeners = List<VoidCallback?>.filled(0, null); ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:106:41: Error: 'VoidCallback' isn't a type. List<VoidCallback?> _listeners = List<VoidCallback?>.filled(0, null); ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:172:20: Error: 'VoidCallback' isn't a type. void addListener(VoidCallback listener) { ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:176:27: Error: 'VoidCallback' isn't a type. _listeners = List<VoidCallback?>.filled(1, null); ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:178:20: Error: 'VoidCallback' isn't a type. final List<VoidCallback?> newListeners = ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:179:18: Error: 'VoidCallback' isn't a type. List<VoidCallback?>.filled(_listeners.length * 2, null); ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:197:18: Error: 'VoidCallback' isn't a type. final List<VoidCallback?> newListeners = List<VoidCallback?>.filled(_count, null); ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:197:53: Error: 'VoidCallback' isn't a type. final List<VoidCallback?> newListeners = List<VoidCallback?>.filled(_count, null); ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:232:23: Error: 'VoidCallback' isn't a type. void removeListener(VoidCallback listener) { ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:235:13: Error: 'VoidCallback' isn't a type. final VoidCallback? _listener = _listeners[i]; ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:334:20: Error: 'VoidCallback' isn't a type. final List<VoidCallback?> newListeners = List<VoidCallback?>.filled(newLength, null); ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:334:55: Error: 'VoidCallback' isn't a type. final List<VoidCallback?> newListeners = List<VoidCallback?>.filled(newLength, null); ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:338:17: Error: 'VoidCallback' isn't a type. final VoidCallback? listener = _listeners[i]; ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:372:20: Error: 'VoidCallback' isn't a type. void addListener(VoidCallback listener) { ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart:379:23: Error: 'VoidCallback' isn't a type. void removeListener(VoidCallback listener) { ^^^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/debug.dart:112:4: Error: 'Brightness' isn't a type. ui.Brightness? debugBrightnessOverride; ^^^^^^^^^^ ../../../../flutter/packages/flutter/lib/src/foundation/key.dart:82:23: Error: The method 'hashValues' isn't defined for the class 'ValueKey'.
> 
> * 'ValueKey' is from 'package:flutter/src/foundation/key.dart' ('../../../../flutter/packages/flutter/lib/src/foundation/key.dart').
>   Try correcting the name to the name of an existing method, or defining a method named 'hashValues'.
>   int get hashCode => hashValues(runtimeType, value);
>   ^^^^^^^^^^
>   ../../../../flutter/packages/flutter/lib/src/foundation/stack_frame.dart:299:23: Error: The method 'hashValues' isn't defined for the class 'StackFrame'.
> * 'StackFrame' is from 'package:flutter/src/foundation/stack_frame.dart' ('../../../../flutter/packages/flutter/lib/src/foundation/stack_frame.dart').
>   Try correcting the name to the name of an existing method, or defining a method named 'hashValues'.
>   int get hashCode => hashValues(number, package, line, column, className, method, source);
>   ^^^^^^^^^^
>   pub finished with exit code 1
> 
> I tried this with a new flutter project as well but still got the same error. Works fine on 1.0.0+7 version

fix has been released with api level 32 on android
