### ISSUE TITLE
android:exported ="true" not working

### ISSUE THREAD

**Issue by lotustha** [evilrat/flutter_zoom_sdk#68]
com.evilratt.flutter_zoom_sdk.CustomWaitActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]
Error launching application on SM G985F.

**Comment by evilrat** [comment]
use latest version of plugin.....

**Comment by lotustha** [comment]
using the latest version bro... still not working

**Comment by Roopaish** [comment]
> using the latest version bro... still not working

You can add it by going to dependecies>direct dependecies>flutter_zoom_sdk>android>src>main>AndroidManifest.xml

![image](https://user-images.githubusercontent.com/54392112/159735203-b749a61d-3a23-4809-bdfc-39aafc394655.png)

**Comment by moradoronline** [comment]
Same here... the best would be to place in documentation about this. And exactly in which session it would be placed... like this:

Edit: 

<activity
    android:name=".MainActivity"
    android:exported="true"
    android:theme="@style/Theme.MyApplication.NoActionBar">
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>
</activity>

**Comment by moradoronline** [comment]
Worked here too. It would be good to place this into the instructions.
