### ISSUE TITLE
App crashes on real device but runs on emulator

### ISSUE THREAD

**Issue by avonwagle** [evilrat/flutter_zoom_sdk#7]
I extracted the example folder only and added plugin to the pubsec file.The app runs perfectly on emulator but after building and running on andriod phone, when i press create meeting or join meeting the app crashes. Can you help me out on this?

**Comment by evilrat** [comment]
> I extracted the example folder only and added plugin to the pubsec file.The app runs perfectly on emulator but after building and running on andriod phone, when i press create meeting or join meeting the app crashes. Can you help me out on this?

share log & you are running on ios or android

**Comment by avonwagle** [comment]
I am running on my andriod phone.

**Comment by evilrat** [comment]
> I am running on my andriod phone.

which branch are you using dev or master.......master branch is working fine

**Comment by avonwagle** [comment]
I am running on master branch. Here is my code

https://drive.google.com/file/d/1nBtxYlq1nfbSfAdii44ql7vmfJ7pA6MX/view?usp=sharing

Can you just give it a look.it runs on emulator but crashes on android when i press any buttons

**Comment by evilrat** [comment]
Ok ....give me some time to verify your code

**Comment by avonwagle** [comment]
Ok. looking forward for your reply

**Comment by evilrat** [comment]
> Ok. looking forward for your reply

i checked it......it is working fine....you need to pass api key & secret to the meeting_screen and start_meeting _screen for join & start meeting respectively....if your are still facing the issue please share crash log for better understanding

**Comment by avonwagle** [comment]
I have added my zoom apikey, appsecret along with meetingid and password for creating meeting. It works on emulator no issues but on my device it says as video.
For crash log how can i get ithttps://user-images.githubusercontent.com/35020650/126858004-53060cf5-255c-4f87-a7a5-fccbe88dc80e.mp4

**Comment by evilrat** [comment]
> I have added my zoom apikey, appsecret along with meetingid and password for creating meeting. It works on emulator no issues but on my device it says as video.
> 
>  mobizen_20210724_104750.mp4 
> And For crash log how can i get it?

Start meeting sloses app?

**Comment by evilrat** [comment]
> I have added my zoom apikey, appsecret along with meetingid and password for creating meeting. It works on emulator no issues but on my device it says as video.
> 
>  mobizen_20210724_104750.mp4 
> And For crash log how can i get it?

make sure to keep minSdkVersion to 21 or +

Progruard also need to be there

-keep class us.zoom.{*;}
-keep class com.zipow.{;}
-keep class us.zipow.**{;}
-keep class org.webrtc.{*;}
-keep class us.google.protobuf.{;}
-keep class com.google.crypto.tink.**{;}
-keep class androidx.security.crypto.**{*;}


buildTypes {
release {
signingConfig signingConfigs.release
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' //add this line
}
}

add this on app level build Gradle

**Comment by evilrat** [comment]
> -keep class us.zoom.{_;} -keep class com.zipow.{;} -keep class us.zipow.**{;} -keep class org.webrtc.{_;}
> -keep class us.google.protobuf.{;}
> -keep class com.google.crypto.tink.**{;} -keep class androidx.security.crypto.**{*;}

**Comment by evilrat** [comment]
> > I have added my zoom apikey, appsecret along with meetingid and password for creating meeting. It works on emulator no issues but on my device it says as video.
> > mobizen_20210724_104750.mp4
> > And For crash log how can i get it?
> 
> make sure to keep minSdkVersion to 21 or +
> 
> Progruard also need to be there
> 
> -keep class us.zoom.{_;} -keep class com.zipow.{;} -keep class us.zipow.**{;} -keep class org.webrtc.{_;}
> -keep class us.google.protobuf.{;}
> -keep class com.google.crypto.tink.**{;} -keep class androidx.security.crypto.**{*;}
> 
> buildTypes {
> release {
> signingConfig signingConfigs.release
> proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' //add this line
> }
> }
> 
> add this on app level build Gradle

create file 'proguard-rules.pro' inside android/app/

**Comment by avonwagle** [comment]
This is  my build gradle setting
    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.evilratt.flutter_zoom_sdk_example"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    buildTypes {
        release {

            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' //add this line
        }
    }
}


and this is my proguard rules

-keep class us.zoom.{;}
-keep class com.zipow.{;}
-keep class us.zipow.**{;}
-keep class org.webrtc.{;}
-keep class us.google.protobuf.{;}
-keep class com.google.crypto.tink.{;}
-keep class androidx.security.crypto.{*;}


Now when i build my apk i get this issue

 Building with sound null safety 

Running Gradle task 'assembleRelease'...                        















C:\Flutter\code\example\android\app\proguard-rules.pro:1:22: R8: Expected char '}' at C:\Flutter\code\example\android\app\proguard-rules.pro:1:22
-keep class us.zoom.{;}
                     ^

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: offset: 21, line: 1, column: 22, origin: C:\Flutter\code\example\android\app\proguard-rules.pro

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Running Gradle task 'assembleRelease'...                            4.6s
[!] The shrinker may have failed to optimize the Java bytecode.
    To disable the shrinker, pass the `--no-shrink` flag to this command.
    To learn more, see: https://developer.android.com/studio/build/shrink-code
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1

**Comment by avonwagle** [comment]
kept minSdkVersion to 21 or +

added the proguard rules and linked on andriod/app

But the issue is same.

Can you build test on real device and provide me the link of the code. i will chnage the appid and password with my zoom acct and test it. It would be great if you could provide me this.
