### ISSUE TITLE
Duplicate class com.google.android.exoplayer2.ui.package-info found in modules jetified-exoplayer-common-2.15.0-runtime (com.google.android.exoplayer:exoplayer-common:2.15.0) and jetified-exoplayer-ui-2.12.3-runtime (com.google.android.exoplayer:exoplayer-ui:2.12.3) (Android)

### ISSUE THREAD

**Issue by Abdullatif-Eida** [evilrat/flutter_zoom_sdk#70]
**To Reproduce (i.e. user steps, not code)**
1. Go to ' you android phone open pubspec.yaml and add  just_audio (https://pub.dev/packages/just_audio)'
2. Click on 'run flutter pub get then run your app'
3. See error

**Error messages**

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.exoplayer2.ui.package-info found in modules jetified-exoplayer-common-2.15.0-runtime (com.google.android.exoplayer:exoplayer-common:2.15.0) and jetified-exoplayer-ui-2.12.3-runtime (com.google.android.exoplayer:exoplayer-ui:2.12.3)

     Go to the documentation to learn how to <a href="d.android.com[/r/tools/classpath-sync-errors]()">Fix dependency resolution errors<[/a]()>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

If applicable, copy & paste error message here, within the triple quotes to preserve formatting.
no opy & paste error message

**Expected behavior**
i am Expecting my app to run without any problem 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS Big Sur + 11.6.2]
 - Browser [e.g. chrome + 99.0.4844.82]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3 a]
 - OS: [e.g. Android Tiramisu]

**Flutter SDK version**
environment:
  sdk: ">=2.16.1 <3.0.0"

Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (3 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2

insert output of "flutter doctor" here
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6.2 20G314 darwin-x64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

**Additional context**
I am trying to use https://pub.dev/packages/just_audio package and the flutter_zoom_sdk and I am facing this error 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.exoplayer2.ui.package-info found in modules jetified-exoplayer-common-2.15.0-runtime (com.google.android.exoplayer:exoplayer-common:2.15.0) and jetified-exoplayer-ui-2.12.3-runtime (com.google.android.exoplayer:exoplayer-ui:2.12.3)
   
Go to the documentation to learn how to <a href="d.android.com[/r/tools/classpath-sync-errors]()">Fix dependency resolution errors<[/a]()>.

is there any solution 

Note: when deleting one of mentioned packages from pubspec.yaml the app run without any problem

**Comment by Abdullatif-Eida** [comment]
I solved the problem 
to solve it fo to android > app > build.gradle > dependencies and add this line
implementation ('com.google.android.exoplayer:exoplayer-ui:2.14.1')

**Comment by Abdullatif-Eida** [comment]
If you can modify the package that will be better

**Comment by evilrat** [comment]
> **To Reproduce (i.e. user steps, not code)** Steps to reproduce the behavior:
> 
> 1. Go to ' you android phone open pubspec.yaml and add  just_audio (https://pub.dev/packages/just_audio)'
> 2. Click on 'run flutter pub get then run your app'
> 3. See error
> 
> **Error messages**
> 
> * What went wrong:
>   Execution failed for task ':app:checkDebugDuplicateClasses'.
> 
> > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
> > Duplicate class com.google.android.exoplayer2.ui.package-info found in modules jetified-exoplayer-common-2.15.0-runtime (com.google.android.exoplayer:exoplayer-common:2.15.0) and jetified-exoplayer-ui-2.12.3-runtime (com.google.android.exoplayer:exoplayer-ui:2.12.3)
> 
> ```
>  Go to the documentation to learn how to <a href="d.android.com[/r/tools/classpath-sync-errors]()">Fix dependency resolution errors<[/a]()>.
> ```
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> If applicable, copy & paste error message here, within the triple quotes to preserve formatting. no opy & paste error message
> 
> **Expected behavior** i am Expecting my app to run without any problem
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. MacOS Big Sur + 11.6.2]
> * Browser [e.g. chrome + 99.0.4844.82]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. Pixel 3 a]
> * OS: [e.g. Android Tiramisu]
> 
> **Flutter SDK version** environment: sdk: ">=2.16.1 <3.0.0"
> 
> Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git Framework • revision 7e9793dee1 (3 weeks ago) • 2022-03-02 11:23:12 -0600 Engine • revision bd539267b4 Tools • Dart 2.16.1 • DevTools 2.9.2
> 
> insert output of "flutter doctor" here [✓] Flutter (Channel stable, 2.10.3, on macOS 11.6.2 20G314 darwin-x64, locale en-TR) [✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1) [✓] Xcode - develop for iOS and macOS (Xcode 13.2.1) [✓] Chrome - develop for the web [✓] Android Studio (version 2021.1) [✓] VS Code (version 1.65.2) [✓] Connected device (4 available) [✓] HTTP Host Availability
> 
> **Additional context** I am trying to use https://pub.dev/packages/just_audio package and the flutter_zoom_sdk and I am facing this error
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:checkDebugDuplicateClasses'.
> 
> > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
> > Duplicate class com.google.android.exoplayer2.ui.package-info found in modules jetified-exoplayer-common-2.15.0-runtime (com.google.android.exoplayer:exoplayer-common:2.15.0) and jetified-exoplayer-ui-2.12.3-runtime (com.google.android.exoplayer:exoplayer-ui:2.12.3)
> 

> Go to the documentation to learn how to [Fix dependency resolution errors<](d.android.com[/r/tools/classpath-sync-errors]())/a>.
> 
> is there any solution
> 
> Note: when deleting one of mentioned packages from pubspec.yaml the app run without any problem

**Refer to this issue :-** https://github.com/evilrat/flutter_zoom_sdk/issues/46

**Comment by evilrat** [comment]
> If you can modify the package that will be better

Currently not possible to do so.......will do it as soon as possible.....PR is always welcome

**Comment by rashidgondal** [comment]
I face this issue today. The flutter-zoom-sdk uses com.google.android.exoplayer-ui: 2.12.3 and just-audio uses com.google.android.exoplayer-ui: 2.15.0. 
We need to downgrade to the just_audio: ^0.9.10 version.
Please change the same version in the pub_lock file because it always takes the latest version. 
Delete the just-audio folder in pub_cache.
flutter clean
flutter pub get 
Run the project.
if you still getting errors, I am ready to help.

**Comment by Abdullatif-Eida** [comment]
@rashidgondal 
No thanks I solved the problem. Follow the steps down to solve it with out changing just audio version 
Go to
android > app > build.gradle > dependencies and add this line
implementation ('com.google.android.exoplayer:exoplayer-ui:2.14.1')

**Comment by kheson77** [comment]
@rashidgondal 

This is the problem after I tried to try.

> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
> Duplicate class com.google.android.exoplayer2.ui.DownloadNotificationHelper found in modules jetified-exoplayer-core-2.17.1-runtime (com.google.android.exoplayer:exoplayer-core:2.17.1) and jetified-exoplayer-ui-2.14.1-runtime (com.google.android.exoplayer:exoplayer-ui:2.14.1)

Can you help me?

**Comment by Abdullatif-Eida** [comment]
Go to
android > app > build.gradle > dependencies and add this line
implementation ('com.google.android.exoplayer:exoplayer-ui:2.14.1')
This solution work for just_audio: ^0.9.20 which is the last version of it. also I talked with the owner and he said he will update the documention of the package to tell people how to solve the problem
take a look to
https://github.com/ryanheise/just_audio/issues/693
