### ISSUE TITLE
AAPT: error: attribute fastforward_increment (aka com.app.thinknativetech:fastforward_increment) not found.

### ISSUE THREAD

**Issue by waqas-alii** [evilrat/flutter_zoom_sdk#73]
After updating to latest versions (  flutter_zoom_sdk: ^1.1.0+4)
 im getting this error anyone knows how to get rid of this?

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/purelogics/.gradle/caches/transforms-2/files-2.1/5ea266ede6e1c385e6af19f7bc82de34/jetified-mobilertc/res/layout/activity_media_player.xml:7: AAPT: error: attribute fastforward_increment (aka com.app.thinknativetech:fastforward_increment) not found.

     /Users/purelogics/.gradle/caches/transforms-2/files-2.1/5ea266ede6e1c385e6af19f7bc82de34/jetified-mobilertc/res/layout/activity_media_player.xml:7: AAPT: error: attribute rewind_increment (aka com.app.thinknativetech:rewind_increment) not found.

     /Users/purelogics/.gradle/caches/transforms-2/files-2.1/5ea266ede6e1c385e6af19f7bc82de34/jetified-mobilertc/res/layout/zm_content_file_video_viewer.xml:8: AAPT: error: attribute fastforward_increment (aka com.app.thinknativetech:fastforward_increment) not found.

     /Users/purelogics/.gradle/caches/transforms-2/files-2.1/5ea266ede6e1c385e6af19f7bc82de34/jetified-mobilertc/res/layout/zm_content_file_video_viewer.xml:8: AAPT: error: attribute rewind_increment (aka com.app.thinknativetech:rewind_increment) not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by waqas-alii** [comment]
@evilrat can you please help here ?

**Comment by ark-brighthustle** [comment]
> @evilrat can you please help here ?

this is due to exoplayer different versions from different plugin

**Comment by Subhajit1999** [comment]
> 

Can you suggest a fix for this? I am facing the same issue.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\hp\.gradle\caches\transforms-2\files-2.1\a8109ef630dc3523bc9e99d40d97cd45\jetified-mobilertc\res\layout\activity_media_player.xml:7: AAPT: error: attribute fastforward_increment (aka org.teamstree.mobile.stree:fastforward_increment) not found.

     C:\Users\hp\.gradle\caches\transforms-2\files-2.1\a8109ef630dc3523bc9e99d40d97cd45\jetified-mobilertc\res\layout\activity_media_player.xml:7: AAPT: error: attribute rewind_increment (aka org.teamstree.mobile.stree:rewind_increment) not found.

     C:\Users\hp\.gradle\caches\transforms-2\files-2.1\a8109ef630dc3523bc9e99d40d97cd45\jetified-mobilertc\res\layout\zm_content_file_video_viewer.xml:8: AAPT: error: attribute fastforward_increment (aka org.teamstree.mobile.stree:fastforward_increment) not found.

     C:\Users\hp\.gradle\caches\transforms-2\files-2.1\a8109ef630dc3523bc9e99d40d97cd45\jetified-mobilertc\res\layout\zm_content_file_video_viewer.xml:8: AAPT: error: attribute rewind_increment (aka org.teamstree.mobile.stree:rewind_increment) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 13s
Exception: Gradle task assembleDebug failed with exit code 1
