### ISSUE TITLE
Getting error while building code

### ISSUE THREAD

**Issue by edmirmob** [evilrat/flutter_zoom_sdk#74]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find :commonlib:.
     Searched in the following locations:
       - fil[e:/C]():/Development/exapmple/example/packages/flutter_zoom_sdk/android/libs/commonlib.aar
     Required by:
         project :app > project :flutter_zoom_sdk
   > Could not find :mobilertc:.
     Searched in the following locations:
       - fil[e:/C]():/Development/example/example/packages/flutter_zoom_sdk/android/libs/mobilertc.aar

Seems like it is not able to locate commonlib and mobilertc plugins used by the [flutter_zoom_sdk] package

**Comment by ark-brighthustle** [comment]
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:checkDebugAarMetadata'.
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
>    > Could not find :commonlib:.
>      Searched in the following locations:
>        - fil[e:/C]():/Development/exapmple/example/packages/flutter_zoom_sdk/android/libs/commonlib.aar
>      Required by:
>          project :app > project :flutter_zoom_sdk
>    > Could not find :mobilertc:.
>      Searched in the following locations:
>        - fil[e:/C]():/Development/example/example/packages/flutter_zoom_sdk/android/libs/mobilertc.aar
> 
> 
> 
> Seems like it is not able to locate commonlib and mobilertc plugins used by the [flutter_zoom_sdk] package
> 

Did u run
 flutter pub run flutter_zoom_sdk:unzip_zoom_sdk

**Comment by edmirmob** [comment]
> flutter pub run flutter_zoom_sdk:unzip_zoom_sdk

yes, I did. I get the same error

**Comment by ark-brighthustle** [comment]
Can you share the complete log....from console

**Comment by edmirmob** [comment]
> flutter pub run flutter_zoom_sdk:unzip_zoom_sdk

in the end I did. in console I navigated to the plugin inserted then I ran flutter pub run flutter_zoom_sdk: unzip_zoom_sdk

**Comment by ark-brighthustle** [comment]
> > flutter pub run flutter_zoom_sdk:unzip_zoom_sdk
> 
> in the end I did. in console I navigated to the plugin inserted then I ran flutter pub run flutter_zoom_sdk: unzip_zoom_sdk

did u solved the issue......

**Comment by edmirmob** [comment]
> > > flutter pub run flutter_zoom_sdk:unzip_zoom_sdk
> > 
> > 
> > in the end I did. in console I navigated to the plugin inserted then I ran flutter pub run flutter_zoom_sdk: unzip_zoom_sdk
> 
> did u solved the issue......

yes, I did. Thank you

**Comment by mishoarafa** [comment]
> > flutter pub run flutter_zoom_sdk:unzip_zoom_sdk
> 
> in the end I did. in console I navigated to the plugin inserted then I ran flutter pub run flutter_zoom_sdk: unzip_zoom_sdk

could you determine which plugin you navigated to before running "flutter_zoom_sdk: unzip_zoom_sdk" again??
