### ISSUE TITLE
App Crashes on Release build

### ISSUE THREAD

**Issue by abhishekts** [evilrat/flutter_zoom_sdk#8]
Hi @evilrat , Hope you're doing good...
We could see a strange thing that whenever we run the app where flutter_zoom_sdk plugin is installed on the debug mode , the app works fine and we could able to join the meetings. But when we build a release APK and try joining the meetings , the app is getting crashed and closes. Not able to capture the error or log. Kindly assist with this issue.

**Comment by abhishekts** [comment]
> Hi @evilrat , Hope you're doing good...
> We could see a strange thing that whenever we run the app where flutter_zoom_sdk plugin is installed on the debug mode , the app works fine and we could able to join the meetings. But when we build a release APK and try joining the meetings , the app is getting crashed and closes. Not able to capture the error or log. Kindly assist with this issue.

@evilrat this is not an issue , as we need to add progaurd rules in the progaurd config file for Android. Rules as below , kindly confirm if anything more to be added.
-keep class us.zoom.** { *; }
-keep class com.zipow.** { *; }
-keep class us.zipow.** { *; }
-keep class org.webrtc.** { *; }
-keep class us.google.protobuf.** { *; }
-keep class com.google.crypto.tink.** { *; }
-keep class androidx.security.crypto.** { *; }

**Comment by evilrat** [comment]
No.....its fine....just add proguard rules

**Comment by Manojdaiya1992** [comment]
Hi @evilrat  
I create a prodguard_rules.pro file under android -> app 
My properties inside the file are 

-keep class  us.zoom.**{*;}
-keep class  com.zipow.**{*;}
-keep class  us.zipow.**{*;}
-keep class  org.webrtc.**{*;}
-keep class  us.google.protobuf.**{*;}
-keep class  com.google.crypto.tink.**{*;}
-keep class  androidx.security.crypto.**{*;}


and my build.gradle under android -> app 

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 32
    ndkVersion flutter.ndkVersion

    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutter_zoom"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
        minSdkVersion 21
        targetSdkVersion 32
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true

    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug

        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}


command i use to create build -> flutter build apk --no-shrink

What else i need to configure. My application is still crashing while joining the meeting
