### ISSUE TITLE
"Waiting for the host to start the meeting" from the host side

### ISSUE THREAD

**Issue by Subhajit1999** [evilrat/flutter_zoom_sdk#82]
We are using Zoom API to create meetings from our server with a given date, and time. And getting the result data through API in the app. and then letting users join the meeting from the result data. But every time it's showing "Waiting for the host to start the meeting" even from the host side. I am passing the email used to create the meeting as userID to the flutter plugin.

Can you tell me the way to join an existing meeting as host with a meeting id and passcode already created?
#
Thank you in advance.

**Comment by ark-brighthustle** [comment]
You can pass meeting id and passcode

**Comment by Subhajit1999** [comment]
> You can pass meeting id and passcode

@evilrat I am passing these already after initializing with SDK app key and secret. But one thing I found on the official Android SDK doc. It's saying passing jwt token is necessary. Can you clarify this?

According to the doc -
_"SDK keys and secrets are vital for Zoom to identify who and which application is calling for Zoom SDK services. To authenticate with Zoom, you must generate a JWT using your SDK key and secret."_

https://marketplace.zoom.us/docs/sdk/native-sdks/android/getting-started/enter-credentials

**Comment by ark-brighthustle** [comment]
> > You can pass meeting id and passcode
> 
> @evilrat I am passing these already after initializing with SDK app key and secret. But one thing I found on the official Android SDK doc. It's saying passing jwt token is necessary. Can you clarify this?
> 
> According to the doc - _"SDK keys and secrets are vital for Zoom to identify who and which application is calling for Zoom SDK services. To authenticate with Zoom, you must generate a JWT using your SDK key and secret."_
> 
> https://marketplace.zoom.us/docs/sdk/native-sdks/android/getting-started/enter-credentials

we are using old sdk....which doesn't require jwt...only you need to login from same user whose personal meeting id and passcode you want to use
