### ISSUE TITLE
import MobileRTC

### ISSUE THREAD

**Issue by sudhanshujuyal** [evilrat/flutter_zoom_sdk#86]
warning: [CP] Unable to find matching .xcframework slice in 'ios-i386_x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64 x86_64).
    /Users/pearlorganisation/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-1.1.0+4/ios/Classes/SwiftFlutterZoomSdkPlugin.swift:2:8: error: no such module 'MobileRTC'
    import MobileRTC
           ^

**Comment by ark-brighthustle** [comment]
> warning: [CP] Unable to find matching .xcframework slice in 'ios-i386_x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64 x86_64). /Users/pearlorganisation/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-1.1.0+4/ios/Classes/SwiftFlutterZoomSdkPlugin.swift:2:8: error: no such module 'MobileRTC' import MobileRTC ^

currently doesn't support on simulator ---- m1 chip

**Comment by moazelsawaf** [comment]
@evilrat 
The same error appears with Intel chips too.

**Comment by AhmedAbouelkher** [comment]
> @evilrat The same error appears with Intel chips too.

Did you fix the issue?
