### ISSUE TITLE
Not able to create build for iOS and please let me know when the sdk version 31 support will come Please do it on priority as we are not able to update our app

### ISSUE THREAD

**Issue by Manojdaiya1992** [evilrat/flutter_zoom_sdk#94]
Error launching application on iPhone SE (3rd generation)

Launching lib/main.dart on iPhone SE (3rd generation) in debug mode...
Running Xcode build...                                                  
Xcode build done.                                            5.3s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-09-06 18:39:19.193 xcodebuild[15696:134492] Requested but did not find extension point
    with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension
    Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in
    com.apple.dt.IDEWatchSupportCore
    2022-09-06 18:39:19.193 xcodebuild[15696:134492] Requested but did not find extension point
    with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension
    Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in
    com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **

Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/lk/3x52rngn09q7xb6p31tzq4v80000gn/T/flutter_tools.5ZbPpR/flutter_ios_build_temp
        _dir5i4IxH/temporary_xcresult_bundle

    warning: [CP] MobileRTC.xcframework: Unable to find matching slice in
    'ios-i386_x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64
    x86_64) and platform (-iphonesimulator).
    /Users/proficesadmin/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-
    1.1.0+4/ios/Classes/SwiftFlutterZoomSdkPlugin.swift:3:8: error: no such module 'MobileRTC'
    import MobileRTC
           ^
    Command EmitSwiftModule failed with a nonzero exit code
    /Users/proficesadmin/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-
    1.1.0+4/ios/Classes/SwiftFlutterZoomSdkPlugin.swift:3:8: error: no such module 'MobileRTC'
    import MobileRTC
           ^
    error: emit-module command failed with exit code 1 (use -v to see invocation)
    error: emit-module command failed with exit code 1 (use -v to see invocation)
    /Users/proficesadmin/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-
    1.1.0+4/ios/Classes/SwiftFlutterZoomSdkPlugin.swift:3:8: error: no such module 'MobileRTC'
    import MobileRTC
           ^
    Command EmitSwiftModule failed with a nonzero exit code
    /Users/proficesadmin/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-
    1.1.0+4/ios/Classes/SwiftFlutterZoomSdkPlugin.swift:3:8: error: no such module 'MobileRTC'
    import MobileRTC
           ^
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    /Users/proficesadmin/Desktop/nrichmobileapp/nrichmobileapp/nrichlearning/ios/Pods/Pods.xcodep
    roj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0,
    but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'FMDB'
    from project 'Pods')

    Result bundle written to path:
        /var/folders/lk/3x52rngn09q7xb6p31tzq4v80000gn/T/flutter_tools.5ZbPpR/flutter_ios_build_temp
        _dir5i4IxH/temporary_xcresult_bundle

Uncategorized (Xcode): Command EmitSwiftModule failed with a nonzero exit code

Swift Compiler Error (Xcode): No such module 'MobileRTC'
/Users/proficesadmin/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-1.1.
0+4/ios/Classes/SwiftFlutterZoomSdkPlugin.swift:2:7

Could not build the application for the simulator.
Error launching application on iPhone SE (3rd generation).

**Comment by AhmedAbouelkher** [comment]
Did you fix it?

**Comment by Manojdaiya1992** [comment]
Hi all,
    I wrote my own code to integrate zoom in my project.
